/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.telasVendas;

import controladores.ControladorVenda;
import java.awt.Frame;
import java.time.format.DateTimeFormatter;
import javax.swing.SwingUtilities;
import view.telasProduto.DialogConsultaProduto;

/**
 *
 * @author Mario
 */
public class TelaCancelarVenda extends javax.swing.JPanel {

    private entidades.Venda vendaAtual;

    /**
     * Creates new form TelaCancelarVenda
     */
    public TelaCancelarVenda() {
        initComponents();

        // Configuração dos spinners 
        jSpinnerIdVenda.setModel(new javax.swing.SpinnerNumberModel(
                0, // valor inicial
                0, // valor mínimo
                null, // valor máximo (sem limite)
                1 // incremento
        ));

        // O botão de atualizar inicia desativado até que alguma modificação ocorra
        jButtonDesativar.setEnabled(false);
    }
    
    private void abrirDetalhesVenda(entidades.Venda venda) {

        java.awt.Frame frame
                = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        DialogListaProdutosVenda dialog
                = new DialogListaProdutosVenda(frame, venda);

        dialog.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelTitulo = new javax.swing.JLabel();
        jLabelIdVenda = new javax.swing.JLabel();
        jSpinnerIdVenda = new javax.swing.JSpinner();
        jLabelIdVenda1 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jLabelIdCliente = new javax.swing.JLabel();
        jLabelIdVendedor = new javax.swing.JLabel();
        jLabelSituacao = new javax.swing.JLabel();
        jLabelValorTotal = new javax.swing.JLabel();
        jButtonListaProdutos = new javax.swing.JButton();
        jButtonDesativar = new javax.swing.JButton();
        jLabelData = new javax.swing.JLabel();
        jLabelValorIdVenda = new javax.swing.JLabel();
        jLabelValorIdCliente = new javax.swing.JLabel();
        jLabelValorIdVendedor = new javax.swing.JLabel();
        jLabelValorData = new javax.swing.JLabel();
        jLabelValorSituacao = new javax.swing.JLabel();
        jLabelValorValorTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new java.awt.GridBagLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("CANCELAR VENDA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(jLabelTitulo, gridBagConstraints);

        jLabelIdVenda.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdVenda.setText("ID Venda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        add(jLabelIdVenda, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(jSpinnerIdVenda, gridBagConstraints);

        jLabelIdVenda1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdVenda1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIdVenda1.setText("ID Venda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        add(jLabelIdVenda1, gridBagConstraints);

        jButtonBuscar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(this::jButtonBuscarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(jButtonBuscar, gridBagConstraints);

        jLabelIdCliente.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIdCliente.setText("ID Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(jLabelIdCliente, gridBagConstraints);

        jLabelIdVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdVendedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIdVendedor.setText("ID Vendedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(jLabelIdVendedor, gridBagConstraints);

        jLabelSituacao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSituacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSituacao.setText("Situação");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(jLabelSituacao, gridBagConstraints);

        jLabelValorTotal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelValorTotal.setText("Valor total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(jLabelValorTotal, gridBagConstraints);

        jButtonListaProdutos.setBackground(new java.awt.Color(102, 102, 255));
        jButtonListaProdutos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonListaProdutos.setText("Produtos da venda");
        jButtonListaProdutos.addActionListener(this::jButtonListaProdutosActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(jButtonListaProdutos, gridBagConstraints);

        jButtonDesativar.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDesativar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDesativar.setText("Desativar venda");
        jButtonDesativar.addActionListener(this::jButtonDesativarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 3, 18, 0);
        add(jButtonDesativar, gridBagConstraints);

        jLabelData.setForeground(new java.awt.Color(0, 0, 0));
        jLabelData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelData.setText("Data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(jLabelData, gridBagConstraints);

        jLabelValorIdVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValorIdVenda.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorIdVenda.setText("         ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        add(jLabelValorIdVenda, gridBagConstraints);

        jLabelValorIdCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValorIdCliente.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorIdCliente.setText("         ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        add(jLabelValorIdCliente, gridBagConstraints);

        jLabelValorIdVendedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValorIdVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorIdVendedor.setText("         ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        add(jLabelValorIdVendedor, gridBagConstraints);

        jLabelValorData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValorData.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorData.setText("         ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        add(jLabelValorData, gridBagConstraints);

        jLabelValorSituacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValorSituacao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorSituacao.setText("         ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        add(jLabelValorSituacao, gridBagConstraints);

        jLabelValorValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValorValorTotal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorValorTotal.setText("         ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        add(jLabelValorValorTotal, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        int idVenda = (Integer) jSpinnerIdVenda.getValue();

        if (idVenda <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite o ID da venda para buscar.", "Campo Vazio", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Faz a chamada ao Controlador que configuramos anteriormente
        vendaAtual = ControladorVenda.getInstanciaControladorVenda().buscarVendaRepositorio(idVenda);

        if (vendaAtual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Venda não encontrada no sistema.", "Não Localizada", javax.swing.JOptionPane.ERROR_MESSAGE);
            jButtonDesativar.setEnabled(false);
            return;
        }

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        jLabelValorData.setText(vendaAtual.getDataVenda().format(formatter));
        jLabelValorIdVenda.setText(String.valueOf(vendaAtual.getIdVenda()));
        jLabelValorIdCliente.setText(String.valueOf(vendaAtual.getIdClienteVenda()));
        jLabelValorIdVendedor.setText(String.valueOf(vendaAtual.getIdVendedorVenda()));
        jLabelValorSituacao.setText(vendaAtual.getVendaAtiva() ? "Ativa" : "Cancelada");
        jLabelValorValorTotal.setText("R$" + vendaAtual.getValorTotalVenda());

        jButtonDesativar.setEnabled(true);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonListaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaProdutosActionPerformed
        abrirDetalhesVenda(vendaAtual);
    }//GEN-LAST:event_jButtonListaProdutosActionPerformed

    private void jButtonDesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesativarActionPerformed
        int resposta = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Deseja desativar a venda?",
                "Confirmar cancelamento",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
            ControladorVenda.getInstanciaControladorVenda().cancelarVenda(vendaAtual.getIdVenda());
            
            jLabelValorSituacao.setText(vendaAtual.getVendaAtiva() ? "Ativa" : "Cancelada");
            
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Venda desativada com sucesso!",
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
        }
    }//GEN-LAST:event_jButtonDesativarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonDesativar;
    private javax.swing.JButton jButtonListaProdutos;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelIdCliente;
    private javax.swing.JLabel jLabelIdVenda;
    private javax.swing.JLabel jLabelIdVenda1;
    private javax.swing.JLabel jLabelIdVendedor;
    private javax.swing.JLabel jLabelSituacao;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelValorData;
    private javax.swing.JLabel jLabelValorIdCliente;
    private javax.swing.JLabel jLabelValorIdVenda;
    private javax.swing.JLabel jLabelValorIdVendedor;
    private javax.swing.JLabel jLabelValorSituacao;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JLabel jLabelValorValorTotal;
    private javax.swing.JSpinner jSpinnerIdVenda;
    // End of variables declaration//GEN-END:variables
}
