/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.telasVendas;

import view.TelaEscolhaModulo;

/**
 *
 * @author Mario
 */
public class TelaMenuVendas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuVendas.class.getName());

    /**
     * Creates new form TelaMenuVendas
     */
    public TelaMenuVendas() {
        initComponents();
        
        // 1. Maximiza a janela
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        // =================================================================
        // CENTRALIZAÇÃO HORIZONTAL DO MENU LATERAL (jPanelMenu1)
        // =================================================================
        jPanelMenu1.setLayout(new javax.swing.BoxLayout(jPanelMenu1, javax.swing.BoxLayout.Y_AXIS));

        float centroX = java.awt.Component.CENTER_ALIGNMENT;

        // --- DEFINE UMA LARGURA PADRÃO PARA TODOS OS BOTÕES ---
        // 140 pixels de largura por 30 pixels de altura (ajuste como preferir)
        java.awt.Dimension tamanhoBotao = new java.awt.Dimension(140, 37);

        jButtonCadastrarVendas.setMaximumSize(tamanhoBotao);
        jButtonAtualizarVendas.setMaximumSize(tamanhoBotao);
        jButtonConsultarVendas.setMaximumSize(tamanhoBotao);
        jButtonListarVendas.setMaximumSize(tamanhoBotao);
        jButtonCancelarVenda.setMaximumSize(tamanhoBotao);
        jButtonSair.setMaximumSize(tamanhoBotao);
        // -----------------------------------------------------

        // Aplica o alinhamento horizontal no centro para cada componente
        jLabelMenu1.setAlignmentX(centroX);
        jButtonCadastrarVendas.setAlignmentX(centroX);
        jButtonAtualizarVendas.setAlignmentX(centroX);
        jButtonConsultarVendas.setAlignmentX(centroX);
        jButtonListarVendas.setAlignmentX(centroX);
        jButtonCancelarVenda.setAlignmentX(centroX);
        jButtonSair.setAlignmentX(centroX);

        // Reconstrói o menu adicionando pequenos espaçamentos verticais entre eles
        jPanelMenu1.removeAll();
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jLabelMenu1);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonCadastrarVendas);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonAtualizarVendas);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonConsultarVendas);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonListarVendas);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonCancelarVenda);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonSair);

        // =================================================================
        // CENTRALIZAÇÃO HORIZONTAL DA ÁREA DE CONTEÚDO (jPanelTela)
        // =================================================================
        // Mesma lógica: empilha de cima para baixo, centralizado na horizontal
        jPanelTela.setLayout(new javax.swing.BoxLayout(jPanelTela, javax.swing.BoxLayout.Y_AXIS));

        jLabelBemVindo.setAlignmentX(centroX);

        jPanelTela.removeAll();
        jPanelTela.add(javax.swing.Box.createVerticalStrut(20)); // Margem do topo da tela
        jPanelTela.add(jLabelBemVindo);

        // Força a atualização do layout
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMenu1 = new javax.swing.JPanel();
        jLabelMenu1 = new javax.swing.JLabel();
        jButtonCadastrarVendas = new javax.swing.JButton();
        jButtonAtualizarVendas = new javax.swing.JButton();
        jButtonConsultarVendas = new javax.swing.JButton();
        jButtonListarVendas = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonCancelarVenda = new javax.swing.JButton();
        jPanelTela = new javax.swing.JPanel();
        jLabelBemVindo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelMenu1.setBackground(new java.awt.Color(102, 102, 255));

        jLabelMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu1.setText("MENU");

        jButtonCadastrarVendas.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCadastrarVendas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastrarVendas.setText("<html><center>Cadastrar<br>Vendas</center></html>");
        jButtonCadastrarVendas.addActionListener(this::jButtonCadastrarVendasActionPerformed);

        jButtonAtualizarVendas.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAtualizarVendas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtualizarVendas.setText("<html><center>Atualizar<br>Vendas</center></html>");
        jButtonAtualizarVendas.addActionListener(this::jButtonAtualizarVendasActionPerformed);

        jButtonConsultarVendas.setBackground(new java.awt.Color(51, 51, 51));
        jButtonConsultarVendas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarVendas.setText("<html><center>Consultar<br>Vendas</center></html>");
        jButtonConsultarVendas.addActionListener(this::jButtonConsultarVendasActionPerformed);

        jButtonListarVendas.setBackground(new java.awt.Color(51, 51, 51));
        jButtonListarVendas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListarVendas.setText("<html><center>Listar<br>Vendas</center></html>");
        jButtonListarVendas.addActionListener(this::jButtonListarVendasActionPerformed);

        jButtonSair.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(this::jButtonSairActionPerformed);

        jButtonCancelarVenda.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCancelarVenda.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelarVenda.setText("<html><center>Cancelar<br>Venda</center></html>");
        jButtonCancelarVenda.addActionListener(this::jButtonCancelarVendaActionPerformed);

        javax.swing.GroupLayout jPanelMenu1Layout = new javax.swing.GroupLayout(jPanelMenu1);
        jPanelMenu1.setLayout(jPanelMenu1Layout);
        jPanelMenu1Layout.setHorizontalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCancelarVenda, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrarVendas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jButtonConsultarVendas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAtualizarVendas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListarVendas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        jPanelMenu1Layout.setVerticalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCadastrarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAtualizarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelMenu1, java.awt.BorderLayout.LINE_START);

        jPanelTela.setBackground(new java.awt.Color(153, 153, 255));

        jLabelBemVindo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelBemVindo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBemVindo.setText("Bem vindo ao módulo Vendas");

        javax.swing.GroupLayout jPanelTelaLayout = new javax.swing.GroupLayout(jPanelTela);
        jPanelTela.setLayout(jPanelTelaLayout);
        jPanelTelaLayout.setHorizontalGroup(
            jPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );
        jPanelTelaLayout.setVerticalGroup(
            jPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBemVindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelTela, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarVendasActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout do jPanelTela para GridBagLayout (ele vai garantir a centralização)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de cadastro normalmente
        TelaCadastrarVenda telaCadastro = new TelaCadastrarVenda();

        // 4. Cria um painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaCadastro.getBackground()); // Mantém a cor azul de fundo

        // Define o tamanho máximo desejado (450px de largura por 420px de altura)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 420);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);

        // 5. Adiciona a tela de cadastro para preencher esse limitador
        limitadorLargura.add(telaCadastro, java.awt.BorderLayout.CENTER);

        // 6. Configura o GridBagLayout para fixar o limitador morto no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical

        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);

        // 7. Atualiza e renderiza os novos componentes na interface
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonCadastrarVendasActionPerformed

    private void jButtonAtualizarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarVendasActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout do jPanelTela para GridBagLayout (garante a centralização)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de atualização
        TelaAtualizarVenda telaAtualizar = new TelaAtualizarVenda();

        // 4. Cria um painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaAtualizar.getBackground()); // Mantém a cor de fundo padrão da tela

        // Define o tamanho máximo desejado (mesmo padrão de 450px por 420px usado no cadastro)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 500);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);

        // 5. Adiciona a tela de atualização para preencher esse limitador
        limitadorLargura.add(telaAtualizar, java.awt.BorderLayout.CENTER);

        // 6. Configura o GridBagLayout para fixar o limitador morto no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical

        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);

        // 7. Atualiza e renderiza os novos componentes na interface
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonAtualizarVendasActionPerformed

    private void jButtonConsultarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarVendasActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout para GridBagLayout (ele gerencia o alinhamento centralizado perfeitamente)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de consulta normalmente
        TelaConsultarVendas telaConsulta = new TelaConsultarVendas();

        telaConsulta.carregarTabela();

        // 4. Configura as regras de posicionamento do GridBagLayout
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;

        // ATENÇÃO AQUI: Força o painel de consulta a ocupar toda a largura disponível (100%)
        // mas mantém o ponto de ancoragem centralizado horizontalmente.
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = java.awt.GridBagConstraints.BOTH; // Permite que a tabela cresça para os lados e para baixo
        gbc.anchor = java.awt.GridBagConstraints.CENTER;

        // Adiciona uma margem de respiro nas laterais e no topo (20 pixels)
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);

        // 5. Adiciona a tela configurada ao painel principal
        jPanelTela.add(telaConsulta, gbc);

        // 6. Atualiza e renderiza a interface na tela
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonConsultarVendasActionPerformed

    private void jButtonListarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarVendasActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout para GridBagLayout (ele gerencia o alinhamento centralizado perfeitamente)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de consulta normalmente
        TelaListarVendas telaListar = new TelaListarVendas();

        telaListar.carregarTabela();

        // 4. Configura as regras de posicionamento do GridBagLayout
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;

        // ATENÇÃO AQUI: Força o painel de consulta a ocupar toda a largura disponível (100%)
        // mas mantém o ponto de ancoragem centralizado horizontalmente.
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = java.awt.GridBagConstraints.BOTH; // Permite que a tabela cresça para os lados e para baixo
        gbc.anchor = java.awt.GridBagConstraints.CENTER;

        // Adiciona uma margem de respiro nas laterais e no topo (20 pixels)
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);

        // 5. Adiciona a tela configurada ao painel principal
        jPanelTela.add(telaListar, gbc);

        // 6. Atualiza e renderiza a interface na tela
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonListarVendasActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // 1. Instancia a tela de escolha de módulos
        TelaEscolhaModulo telaModulo = new TelaEscolhaModulo();

        // 2. Torna a nova janela visível
        telaModulo.setVisible(true);

        // 3. Centraliza a nova janela no meio do ecrã/monitor
        telaModulo.setLocationRelativeTo(null);

        // 4. Fecha e destrói o JFrame atual do Menu do Funcionario
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarVendaActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout do jPanelTela para GridBagLayout (ele vai garantir a centralização)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de cadastro normalmente
        TelaCancelarVenda telaCadastro = new TelaCancelarVenda();

        // 4. Cria um painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaCadastro.getBackground()); // Mantém a cor azul de fundo

        // Define o tamanho máximo desejado (450px de largura por 420px de altura)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 500);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);

        // 5. Adiciona a tela de cadastro para preencher esse limitador
        limitadorLargura.add(telaCadastro, java.awt.BorderLayout.CENTER);

        // 6. Configura o GridBagLayout para fixar o limitador morto no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical

        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);

        // 7. Atualiza e renderiza os novos componentes na interface
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonCancelarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenuVendas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarVendas;
    private javax.swing.JButton jButtonCadastrarVendas;
    private javax.swing.JButton jButtonCancelarVenda;
    private javax.swing.JButton jButtonConsultarVendas;
    private javax.swing.JButton jButtonListarVendas;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JLabel jLabelMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenu1;
    private javax.swing.JPanel jPanelTela;
    // End of variables declaration//GEN-END:variables
}
