/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.telasVendas;

/**
 *
 * @author Mario
 */
public class TelaListarVendas extends javax.swing.JPanel {

    private java.util.List<entidades.Venda> listaVendas;

    /**
     * Creates new form TelaListarVendas
     */
    public TelaListarVendas() {
        initComponents();

        // 5. Carrega os dados na tabela
        carregarTabela();

        configurarCliqueTabela();

        
    }

    public void carregarTabela() {
        // 1. Pega a lista de funcionarios do seu repositório
        listaVendas = repositorio.Repositorio.getInstanciaRepositorio().getListaVenda();

        // 2. Captura o modelo da tabela para manipular as linhas
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTableListaVendas.getModel();

        // Limpa a tabela antes de carregar
        modelo.setNumRows(0);

        // 3. Varre a lista de funcionarios e adiciona cada um como uma nova linha
        for (entidades.Venda v : listaVendas) {
            modelo.addRow(new Object[]{
                v.getIdVenda(),
                v.getIdClienteVenda(),
                v.getIdVendedorVenda(),
                v.getDataVenda(),
                v.getVendaAtiva() ? "Ativa" : "Cancelada",
                v.getValorTotalVenda()
            });
        }
    }

    private void configurarCliqueTabela() {

        jTableListaVendas.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                if (evt.getClickCount() == 2) {

                    int linha = jTableListaVendas.getSelectedRow();

                    if (linha != -1) {

                        entidades.Venda vendaSelecionada = listaVendas.get(linha);

                        abrirDetalhesVenda(vendaSelecionada);

                    }

                }

            }

        });

    }

    private void abrirDetalhesVenda(entidades.Venda venda) {

        java.awt.Frame frame
                = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        DialogListaProdutosVenda dialog
                = new DialogListaProdutosVenda(frame, venda);

        dialog.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaVendas = new javax.swing.JTable();
        jLabelAviso = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new java.awt.GridBagLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("LISTAR VENDAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(jLabelTitulo, gridBagConstraints);

        jTableListaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Venda", "ID Cliente", "ID Vendedor", "Data", "Situação", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaVendas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 387;
        gridBagConstraints.ipady = 216;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        add(jScrollPane1, gridBagConstraints);

        jLabelAviso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAviso.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAviso.setText("Duplo click na linha da venda para abrir sua lista de produtos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(jLabelAviso, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAviso;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaVendas;
    // End of variables declaration//GEN-END:variables
}
