/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import java.util.List;
import entidades.Funcionario;
import controladores.ControladorLogin;
import repositorio.Repositorio;

/**
 *
 * @author Mario
 */
public class TelaInicial extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());

    /**
     * Creates new form TelaInicial
     */
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();

        // 1. Maximiza a tela para ocupar todo o monitor do usuário
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        // 2. CORREÇÃO DO BACKGROUND: Pinta o fundo do JFrame com o mesmo azul do jPanel1
        // Isso elimina aquela borda cinza gigante quando a tela expande!
        java.awt.Color corAzul = jPanel1.getBackground();
        getContentPane().setBackground(corAzul);

        // 3. Centraliza o jPanel1 no container principal da janela (GridBagLayout)
        getContentPane().setLayout(new java.awt.GridBagLayout());

        java.awt.GridBagConstraints gbcFrame = new java.awt.GridBagConstraints();
        gbcFrame.gridx = 0;
        gbcFrame.gridy = 0;
        gbcFrame.anchor = java.awt.GridBagConstraints.CENTER;
        getContentPane().add(jPanel1, gbcFrame);

        // --- BLOCO DE DESIGN PARA CENTRALIZAR OS COMPONENTES ENTRE SI ---
        // Muda o layout INTERNO do jPanel1 para BoxLayout (Alinhamento em coluna)
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        float centralizado = java.awt.Component.CENTER_ALIGNMENT;
        int espacamento = 10; // Espaço vertical entre os componentes (pixels)

        // Aplica o alinhamento central para o Título
        jLabelTitulo.setAlignmentX(centralizado);

        // Cria um sub-painel para agrupar Usuário e Senha e centralizá-lo
        javax.swing.JPanel painelCampos = new javax.swing.JPanel();
        painelCampos.setLayout(new java.awt.GridBagLayout()); // Usamos GridBagLayout aqui para manter Rótulo:Campo
        painelCampos.setBackground(corAzul); // Garante o fundo azul no sub-painel

        java.awt.GridBagConstraints c = new java.awt.GridBagConstraints();
        c.insets = new java.awt.Insets(5, 5, 5, 5); // Pequenas margens

        // Linha do Usuário
        c.gridx = 0;
        c.gridy = 0;
        painelCampos.add(jLabelUsuario, c);
        c.gridx = 1;

        // Tamanho dos campos
        java.awt.Dimension tamanhoCampo = new java.awt.Dimension(150, 26);
        jTextFieldUsuario.setPreferredSize(tamanhoCampo);
        jTextFieldUsuario.setMinimumSize(tamanhoCampo);
        painelCampos.add(jTextFieldUsuario, c);

        // Linha da Senha
        c.gridx = 0;
        c.gridy = 1;
        painelCampos.add(jLabelSenha, c);
        c.gridx = 1;
        jPasswordFieldSenha.setPreferredSize(tamanhoCampo);
        jPasswordFieldSenha.setMinimumSize(tamanhoCampo);
        painelCampos.add(jPasswordFieldSenha, c);

        // Centraliza o sub-painel de campos e o Botão
        painelCampos.setAlignmentX(centralizado);
        jButtonEntrar.setAlignmentX(centralizado);

        // 4. Reconstrói o jPanel1 na ordem correta, com espaçamentos
        jPanel1.removeAll();

        jPanel1.add(jLabelTitulo);
        jPanel1.add(javax.swing.Box.createVerticalStrut(30)); // Espaço maior abaixo do título
        jPanel1.add(painelCampos);
        jPanel1.add(javax.swing.Box.createVerticalStrut(espacamento));
        jPanel1.add(jButtonEntrar);

        // 5. CORREÇÃO DO BOTÃO: Reatribui o evento de clique que o removeAll() apagou
        jButtonEntrar.addActionListener(this::jButtonEntrarActionPerformed);

        // Define o gatilho do ENTER para o botão de login
        this.getRootPane().setDefaultButton(jButtonEntrar);

        // Revalida e redesenha a tela completa
        getContentPane().revalidate();
        getContentPane().repaint();
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonEntrar = new javax.swing.JButton();
        jPasswordFieldSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("SisGer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 6, 0, 0);
        jPanel1.add(jLabelTitulo, gridBagConstraints);

        jLabelUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUsuario.setText("Usuário");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 121, 0, 0);
        jPanel1.add(jLabelUsuario, gridBagConstraints);

        jLabelSenha.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSenha.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 121, 0, 0);
        jPanel1.add(jLabelSenha, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 6, 0, 144);
        jPanel1.add(jTextFieldUsuario, gridBagConstraints);

        jButtonEntrar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonEntrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(this::jButtonEntrarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 5, 126, 0);
        jPanel1.add(jButtonEntrar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 144);
        jPanel1.add(jPasswordFieldSenha, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        String login = this.jTextFieldUsuario.getText();

        // FORMA CORRETA: Captura como array de char
        char[] senhaArray = jPasswordFieldSenha.getPassword();
        // Converte para String APENAS se o seu controlador exigir uma String
        String senha = new String(senhaArray);
        // Limpa o array da memória logo após o uso por segurança
        java.util.Arrays.fill(senhaArray, '0');

        List<Funcionario> listaFunc = Repositorio.getInstanciaRepositorio().getListaFuncionarios();

        boolean loginSucesso = ControladorLogin.getInstanciaControladorLogin().efetuarLoginGrafico(login, senha, listaFunc);

        if (loginSucesso) {
            // INSTANCIA A PRÓXIMA TELA (como ela está no mesmo pacote 'view', não precisa de import)
            TelaEscolhaModulo telaModulo = new TelaEscolhaModulo();

            // Torna a nova tela visível
            telaModulo.setVisible(true);

            // Opcional: Centraliza a nova tela no meio da tela do computador
            telaModulo.setLocationRelativeTo(null);

            // Fecha/Destrói a tela de login atual para não ficar aberta em segundo plano
            this.dispose();
        } else {
            // Exibe um pop-up com mensagem de erro se falhar
            JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos.", "Erro de Autenticação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
