/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.telasCliente.TelaMenuCliente;
import view.telasFuncionario.TelaMenuFuncionario;
import view.telasProduto.TelaMenuProduto;
import view.telasVendas.TelaMenuVendas;

/**
 *
 * @author Mario
 */
public class TelaEscolhaModulo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEscolhaModulo.class.getName());

    /**
     * Creates new form TelaEscolhaModulo
     */
    public TelaEscolhaModulo() {
        initComponents();
        
        // --- SEU CÓDIGO EDITÁVEL E SEGURO ---
        
        // 1. Maximiza a tela para ocupar todo o monitor do usuário
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        // 2. CORREÇÃO DO BACKGROUND: Pinta o fundo do JFrame com o mesmo roxo do jPanel1
        // Isso elimina a borda cinza quando a janela estica!
        java.awt.Color corRoxa = jPanel1.getBackground();
        getContentPane().setBackground(corRoxa);
        
        // 3. Muda o layout do container principal para GridBagLayout (garante a centralização)
        getContentPane().setLayout(new java.awt.GridBagLayout());
        
        // 4. Configura as regras para o jPanel1 flutuar perfeitamente centralizado
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        
        // 5. Remove o jPanel1 do layout antigo e joga ele no GridBagLayout centralizado
        // Sem tocar nos componentes internos (evitando o erro de GroupLayout)
        getContentPane().add(jPanel1, gbc);
        
        // Revalida e redesenha a tela completa para aplicar o visual
        getContentPane().revalidate();
        getContentPane().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonFuncionario = new javax.swing.JButton();
        jButtonProduto = new javax.swing.JButton();
        jButtonCliente = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonVenda = new javax.swing.JButton();
        jButtonEstoque = new javax.swing.JButton();
        jLabelEscolhaModulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));

        jButtonFuncionario.setBackground(new java.awt.Color(102, 102, 255));
        jButtonFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        jButtonFuncionario.setText("Funcionário");
        jButtonFuncionario.addActionListener(this::jButtonFuncionarioActionPerformed);

        jButtonProduto.setBackground(new java.awt.Color(102, 102, 255));
        jButtonProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonProduto.setForeground(new java.awt.Color(0, 0, 0));
        jButtonProduto.setText("Produto");
        jButtonProduto.addActionListener(this::jButtonProdutoActionPerformed);

        jButtonCliente.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCliente.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCliente.setText("Cliente");
        jButtonCliente.addActionListener(this::jButtonClienteActionPerformed);

        jButtonSair.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(this::jButtonSairActionPerformed);

        jButtonVenda.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVenda.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVenda.setText("Venda");
        jButtonVenda.addActionListener(this::jButtonVendaActionPerformed);

        jButtonEstoque.setBackground(new java.awt.Color(102, 102, 255));
        jButtonEstoque.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEstoque.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEstoque.setText("Estoque");

        jLabelEscolhaModulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEscolhaModulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEscolhaModulo.setText("ESCOLHA O MÓDULO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jButtonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabelEscolhaModulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelEscolhaModulo)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        TelaMenuCliente telaMenuCliente = new TelaMenuCliente();
        telaMenuCliente.setVisible(true);
        telaMenuCliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionarioActionPerformed
        TelaMenuFuncionario telaMenuFuncionario = new TelaMenuFuncionario();
        telaMenuFuncionario.setVisible(true);
        telaMenuFuncionario.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonFuncionarioActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // 1. Instancia a tela de escolha de módulos
        TelaInicial telaInicial = new TelaInicial();

        // 2. Torna a nova janela visível
        telaInicial.setVisible(true);

        // 3. Centraliza a nova janela no meio do ecrã/monitor
        telaInicial.setLocationRelativeTo(null);

        // 4. Fecha e destrói o JFrame atual do Menu do Funcionario
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoActionPerformed
        TelaMenuProduto telaMenuProduto = new TelaMenuProduto();
        telaMenuProduto.setVisible(true);
        telaMenuProduto.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonProdutoActionPerformed

    private void jButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaActionPerformed
        TelaMenuVendas telaMenuVenda = new TelaMenuVendas();
        telaMenuVenda.setVisible(true);
        telaMenuVenda.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEscolhaModulo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonEstoque;
    private javax.swing.JButton jButtonFuncionario;
    private javax.swing.JButton jButtonProduto;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVenda;
    private javax.swing.JLabel jLabelEscolhaModulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
