/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.telasFuncionario;

import controladores.ControladorFuncionario;

/**
 *
 * @author Mario
 */
public class TelaCadastroFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastroFuncionario
     */
    public TelaCadastroFuncionario() {
        initComponents();
        // MASCARAS DE FORMATAÇÃO
        try {
            // CPF
            javax.swing.text.MaskFormatter mascaraCpf = new javax.swing.text.MaskFormatter("###.###.###-##");
            mascaraCpf.setPlaceholderCharacter('_'); // Define o caractere de preenchimento
            jFormattedTextFieldCpfFunc.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascaraCpf)
            );

            // Máscara para Telefone Celular (padrão de 9 dígitos + DDD)
            javax.swing.text.MaskFormatter mascaraTelefone = new javax.swing.text.MaskFormatter("(##) #####-####");
            mascaraTelefone.setPlaceholderCharacter('_');

            // Aplica ao seu componente JFormattedTextField do telefone
            jFormattedTextFieldTelefoneFunc.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascaraTelefone)
            );

            // CEP
            javax.swing.text.MaskFormatter mascaraCep = new javax.swing.text.MaskFormatter("#####-###");
            mascaraCep.setPlaceholderCharacter('_');
            jFormattedTextFieldCepFunc.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascaraCep)
            );

        } catch (java.text.ParseException ex) {
            // Trata um eventual erro de digitação na string da máscara ("###...")
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeFunc = new javax.swing.JLabel();
        jLabelCpfFunc = new javax.swing.JLabel();
        jLabelEmailFunc = new javax.swing.JLabel();
        jLabel1TelefoneFunc = new javax.swing.JLabel();
        jLabelLogradouroFunc = new javax.swing.JLabel();
        jLabelNumeroFunc = new javax.swing.JLabel();
        jLabelBairroFunc = new javax.swing.JLabel();
        jLabelCidadeFunc = new javax.swing.JLabel();
        jLabelEstadoFunc = new javax.swing.JLabel();
        jLabelCepFunc = new javax.swing.JLabel();
        jTextFieldNomeFunc = new javax.swing.JTextField();
        jTextFieldEmailFunc = new javax.swing.JTextField();
        jTextFieldLogradouroFunc = new javax.swing.JTextField();
        jTextFieldNumeroFunc = new javax.swing.JTextField();
        jTextFieldBairroFunc = new javax.swing.JTextField();
        jTextFieldCidadeFunc = new javax.swing.JTextField();
        jComboBoxEstadoFunc = new javax.swing.JComboBox<>();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonCadastrarFunc = new javax.swing.JButton();
        jFormattedTextFieldCpfFunc = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCepFunc = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefoneFunc = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabelNomeFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNomeFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomeFunc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNomeFunc.setText("Nome");

        jLabelCpfFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCpfFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCpfFunc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCpfFunc.setText("CPF");

        jLabelEmailFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmailFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEmailFunc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEmailFunc.setText("E-mail");

        jLabel1TelefoneFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1TelefoneFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1TelefoneFunc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1TelefoneFunc.setText("Telefone");

        jLabelLogradouroFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLogradouroFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLogradouroFunc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLogradouroFunc.setText("Logradouro");

        jLabelNumeroFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNumeroFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumeroFunc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNumeroFunc.setText("Número");

        jLabelBairroFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBairroFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBairroFunc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBairroFunc.setText("Bairro");

        jLabelCidadeFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCidadeFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCidadeFunc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCidadeFunc.setText("Cidade");

        jLabelEstadoFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEstadoFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstadoFunc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEstadoFunc.setText("Estado");

        jLabelCepFunc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCepFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCepFunc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCepFunc.setText("CEP");

        jTextFieldBairroFunc.addActionListener(this::jTextFieldBairroFuncActionPerformed);

        jComboBoxEstadoFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("CADASTRO DE FUNCIONÁRIOS");

        jButtonCadastrarFunc.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCadastrarFunc.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastrarFunc.setText("Cadastrar");
        jButtonCadastrarFunc.addActionListener(this::jButtonCadastrarFuncActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNomeFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLogradouroFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCpfFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmailFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1TelefoneFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNumeroFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelBairroFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCidadeFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEstadoFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCepFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxEstadoFunc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomeFunc)
                    .addComponent(jTextFieldEmailFunc)
                    .addComponent(jTextFieldLogradouroFunc)
                    .addComponent(jTextFieldNumeroFunc)
                    .addComponent(jTextFieldBairroFunc)
                    .addComponent(jTextFieldCidadeFunc)
                    .addComponent(jFormattedTextFieldCpfFunc)
                    .addComponent(jFormattedTextFieldCepFunc)
                    .addComponent(jFormattedTextFieldTelefoneFunc))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jButtonCadastrarFunc)
                .addGap(132, 132, 132))
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeFunc)
                    .addComponent(jTextFieldNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpfFunc)
                    .addComponent(jFormattedTextFieldCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailFunc)
                    .addComponent(jTextFieldEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1TelefoneFunc)
                    .addComponent(jFormattedTextFieldTelefoneFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogradouroFunc)
                    .addComponent(jTextFieldLogradouroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroFunc)
                    .addComponent(jTextFieldNumeroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairroFunc)
                    .addComponent(jTextFieldBairroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidadeFunc)
                    .addComponent(jTextFieldCidadeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstadoFunc)
                    .addComponent(jComboBoxEstadoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCepFunc)
                    .addComponent(jFormattedTextFieldCepFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadastrarFunc)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarFuncActionPerformed
        String nome = jTextFieldNomeFunc.getText().trim();
        String cpf = jFormattedTextFieldCpfFunc.getText().trim();
        String email = jTextFieldEmailFunc.getText().trim();
        String telefone = jFormattedTextFieldTelefoneFunc.getText().trim();
        String logradouro = jTextFieldLogradouroFunc.getText().trim();
        String numero = jTextFieldNumeroFunc.getText().trim();
        String bairro = jTextFieldBairroFunc.getText().trim();
        String cidade = jTextFieldCidadeFunc.getText().trim();
        String cep = jFormattedTextFieldCepFunc.getText().trim();

        // Pega o índice selecionado no ComboBox do Estado
        int estadoIndex = jComboBoxEstadoFunc.getSelectedIndex();

        // =================================================================
        // VALIDAÇÃO: VERIFICAÇÃO DE CAMPOS VAZIOS OU NÃO SELECIONADOS
        // =================================================================
        // Verifica se os campos de texto comuns estão vazios, se o combobox está no "-- Selecione --"
        // ou se os campos formatados contêm apenas os caracteres da máscara vazia.
        if (nome.isEmpty() || email.isEmpty() || logradouro.isEmpty() || numero.isEmpty()
                || bairro.isEmpty() || cidade.isEmpty() || estadoIndex == 0
                || cpf.equals("___.___.___-__") || telefone.equals("(__) _____-____") || cep.equals("_____-___")) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, preencha todos os campos obrigatórios e selecione o Estado!",
                    "Campos Incompletos",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Interrompe a execução aqui se faltar algo
        }

        // Expressão regular padrão para validar se o e-mail possui um formato válido
        String regexEmail = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        // Se o e-mail digitado não bater com o padrão, barra o cadastro
        if (!email.matches(regexEmail)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, insira um endereço de e-mail válido!",
                    "E-mail Inválido",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

            jTextFieldEmailFunc.requestFocus();
            return;
        }

        // =================================================================
        // NOVA VALIDAÇÃO: VERIFICAÇÃO DE CPF DUPLICADO
        // =================================================================
        if (ControladorFuncionario.getInstanciaControladorFuncionario().cpfJaCadastradoFuncionario(cpf)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "O CPF informado (" + cpf + ") já está vinculado a um funcionário cadastrado!",
                    "CPF Duplicado",
                    javax.swing.JOptionPane.WARNING_MESSAGE);

            jFormattedTextFieldCpfFunc.requestFocus(); // Foca o cursor no campo do CPF
            return; // Interrompe o método AQUI. Nada abaixo é executado e os campos NÃO são limpos!
        }
        // =================================================================

        String estado = jComboBoxEstadoFunc.getSelectedItem().toString();

        // 1. Envia os dados para salvar
        int idFuncionario = ControladorFuncionario.getInstanciaControladorFuncionario().cadastrarFuncionarioGrafico(nome, cpf, email, telefone, logradouro, numero, bairro, cidade, estado, cep);

        // =================================================================
        // NOVOS COMPORTAMENTOS: AVISO E LIMPEZA (Só roda se o CPF for inédito)
        // =================================================================
        // 2. Mostra a caixinha de aviso de Sucesso
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Funcionário '" + nome + "' cadastrado com sucesso no ID " + idFuncionario,
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        // 3. Limpa todos os campos da tela
        jTextFieldNomeFunc.setText("");
        jFormattedTextFieldCpfFunc.setValue(null);
        jTextFieldEmailFunc.setText("");
        jFormattedTextFieldTelefoneFunc.setValue(null);
        jTextFieldLogradouroFunc.setText("");
        jTextFieldNumeroFunc.setText("");
        jTextFieldBairroFunc.setText("");
        jTextFieldCidadeFunc.setText("");
        jComboBoxEstadoFunc.setSelectedIndex(0);
        jFormattedTextFieldCepFunc.setValue(null);

        // 4. Coloca o cursor piscando de volta no Nome do funcionario
        jTextFieldNomeFunc.requestFocus();
    }//GEN-LAST:event_jButtonCadastrarFuncActionPerformed

    private void jTextFieldBairroFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroFuncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarFunc;
    private javax.swing.JComboBox<String> jComboBoxEstadoFunc;
    private javax.swing.JFormattedTextField jFormattedTextFieldCepFunc;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfFunc;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefoneFunc;
    private javax.swing.JLabel jLabel1TelefoneFunc;
    private javax.swing.JLabel jLabelBairroFunc;
    private javax.swing.JLabel jLabelCepFunc;
    private javax.swing.JLabel jLabelCidadeFunc;
    private javax.swing.JLabel jLabelCpfFunc;
    private javax.swing.JLabel jLabelEmailFunc;
    private javax.swing.JLabel jLabelEstadoFunc;
    private javax.swing.JLabel jLabelLogradouroFunc;
    private javax.swing.JLabel jLabelNomeFunc;
    private javax.swing.JLabel jLabelNumeroFunc;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldBairroFunc;
    private javax.swing.JTextField jTextFieldCidadeFunc;
    private javax.swing.JTextField jTextFieldEmailFunc;
    private javax.swing.JTextField jTextFieldLogradouroFunc;
    private javax.swing.JTextField jTextFieldNomeFunc;
    private javax.swing.JTextField jTextFieldNumeroFunc;
    // End of variables declaration//GEN-END:variables
}
