/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.telasFuncionario;

import controladores.ControladorFuncionario;
import javax.swing.ButtonGroup;

/**
 *
 * @author Mario
 */
public class TelaCargoFuncionario extends javax.swing.JPanel {

    private entidades.Funcionario funcionarioAtual; // Armazena o funcionario localizado
    private boolean escutadorAtivo = false;

    /**
     * Creates new form TelaCargoFuncionario
     */
    public TelaCargoFuncionario() {
        initComponents();

        configurarGrupoBotoes();
        configurarMascaras(); // Inicializa as máscaras internas (salário/data)

        // CORREÇÃO: Força o campo de busca a iniciar sem máscara (já que ID inicia selecionado)
        jFormattedTextFieldBusca.setFormatterFactory(null);
        jFormattedTextFieldBusca.setText("");

        // Adiciona monitoramento à caixa de seleção do Cargo
        jComboBoxCargo.addActionListener(e -> verificarCampos());
        configurarEventosBusca();

        jButtonAlterarCargo.setEnabled(false);
    }

    // Une os RadioButtons para que funcionem de forma exclusiva (marcar um desmarca o outro)
    private void configurarGrupoBotoes() {
        ButtonGroup grupoBusca = new ButtonGroup();
        grupoBusca.add(jRadioButtonId);
        grupoBusca.add(jRadioButtonCpf);
        jRadioButtonId.setSelected(true); // ID inicia selecionado por padrão
    }

    private void configurarEventosBusca() {
        // Evento para quando selecionar ID: remove a máscara
        jRadioButtonId.addActionListener(e -> {
            jFormattedTextFieldBusca.setFormatterFactory(null);
            jFormattedTextFieldBusca.setText("");
            jFormattedTextFieldBusca.requestFocus();
        });

        // Evento para quando selecionar CPF: aplica a máscara
        jRadioButtonCpf.addActionListener(e -> {
            try {
                javax.swing.text.MaskFormatter mascaraCpfBusca = new javax.swing.text.MaskFormatter("###.###.###-##");
                mascaraCpfBusca.setPlaceholderCharacter('_');
                jFormattedTextFieldBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraCpfBusca));
                jFormattedTextFieldBusca.setText("");
                jFormattedTextFieldBusca.requestFocus();
            } catch (java.text.ParseException ex) {
                java.util.logging.Logger.getLogger(TelaAtualizarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        });
    }

    private void configurarMascaras() {
        try {
            // =================================================================
            // MÁSCARA DO CPF (CAMPO DE BUSCA)
            // =================================================================
            javax.swing.text.MaskFormatter mascaraCpf = new javax.swing.text.MaskFormatter("###.###.###-##");
            mascaraCpf.setPlaceholderCharacter('_');
            jFormattedTextFieldBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraCpf));

        } catch (java.text.ParseException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarFuncionarios.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Erro ao configurar as máscaras dos campos", ex);
        }
    }

    private void verificarCampos() {
        // Se o escutador não estiver ativo ou o funcionário não foi buscado, mantém desativado
        if (!escutadorAtivo || funcionarioAtual == null) {
            jButtonAlterarCargo.setEnabled(false);
            return;
        }

        boolean cargoValido
                = jComboBoxCargo.getSelectedIndex() > 0
                && !jComboBoxCargo.getSelectedItem().equals(funcionarioAtual.getCargo());

        jButtonAlterarCargo.setEnabled(cargoValido);
    }

    private void limparFormulario() {
        escutadorAtivo = false;
        funcionarioAtual = null;
        jLabelNomeFunc.setText("");
        jLabelCpfFunc.setText("");
        jLabelCargoAtualFunc.setText("");
        jFormattedTextFieldBusca.setText("");
        jComboBoxCargo.setSelectedIndex(0);
        jButtonAlterarCargo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCargo = new javax.swing.JComboBox<>();
        jLabelCpf = new javax.swing.JLabel();
        jButtonAlterarCargo = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jLabelCargo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jRadioButtonId = new javax.swing.JRadioButton();
        jRadioButtonCpf = new javax.swing.JRadioButton();
        jFormattedTextFieldBusca = new javax.swing.JFormattedTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabelNomeFunc = new javax.swing.JLabel();
        jLabelCpfFunc = new javax.swing.JLabel();
        jLabelCargoAtual = new javax.swing.JLabel();
        jLabelCargoAtualFunc = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --", "Vendedor", "Estoquista", "Gerente de Vendas", "Gerente de Estoque" }));

        jLabelCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCpf.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCpf.setText("CPF");

        jButtonAlterarCargo.setBackground(new java.awt.Color(102, 102, 255));
        jButtonAlterarCargo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAlterarCargo.setText("Alterar Cargo");
        jButtonAlterarCargo.addActionListener(this::jButtonAlterarCargoActionPerformed);

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNome.setText("Nome");

        jLabelCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCargo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCargo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCargo.setText("Novo cargo");

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("ALTERAR CARGO");

        jRadioButtonId.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonId.setText("ID");

        jRadioButtonCpf.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonCpf.setText("CPF");

        jButtonBuscar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(this::jButtonBuscarActionPerformed);

        jLabelNomeFunc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNomeFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomeFunc.setText("          ");

        jLabelCpfFunc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCpfFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCpfFunc.setText("          ");

        jLabelCargoAtual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCargoAtual.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCargoAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCargoAtual.setText("Cargo atual");

        jLabelCargoAtualFunc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCargoAtualFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCargoAtualFunc.setText("          ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonId)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonCpf))
                    .addComponent(jFormattedTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jButtonBuscar))
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNomeFunc))
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCpfFunc))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelCargoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCargoAtualFunc))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButtonAlterarCargo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitulo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonId)
                            .addComponent(jRadioButtonCpf))
                        .addGap(6, 6, 6)
                        .addComponent(jFormattedTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButtonBuscar)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelNomeFunc))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCpf)
                    .addComponent(jLabelCpfFunc))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCargoAtual)
                    .addComponent(jLabelCargoAtualFunc))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCargo)
                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterarCargo))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarCargoActionPerformed
        // 1. Pega o ID e o Cargo normalmente
        String cargo = jComboBoxCargo.getSelectedItem().toString();

        // CHAMA O MÉTODO DO CONTROLADOR
        ControladorFuncionario.getInstanciaControladorFuncionario().alteraCargo(funcionarioAtual, cargo);

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Cargo do Funcionário alterado com sucesso!",
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Limpa os campos após o sucesso
        limparFormulario();
        jFormattedTextFieldBusca.requestFocus();
    }//GEN-LAST:event_jButtonAlterarCargoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String termo = jFormattedTextFieldBusca.getText().trim();
        String tipoBusca = jRadioButtonId.isSelected() ? "ID" : "CPF";

        if (termo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite o ID ou CPF para buscar.", "Campo Vazio", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Faz a chamada ao Controlador que configuramos anteriormente
        funcionarioAtual = ControladorFuncionario.getInstanciaControladorFuncionario().buscarFuncionarioPorIdOuCpf(tipoBusca, termo);

        if (funcionarioAtual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Funcionário não encontrado no sistema.", "Não Localizado", javax.swing.JOptionPane.ERROR_MESSAGE);
            jButtonAlterarCargo.setEnabled(false);
            return;
        }

        escutadorAtivo = false; // Bloqueia validações enquanto preenche o cabeçalho

        jLabelNomeFunc.setText(funcionarioAtual.getNome());
        jLabelCpfFunc.setText(funcionarioAtual.getCpf());
        jLabelCargoAtualFunc.setText(funcionarioAtual.getCargo());

        escutadorAtivo = true; // Libera o monitoramento dos campos do formulário
        verificarCampos();     // Executa a primeira verificação do estado atual
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarCargo;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JFormattedTextField jFormattedTextFieldBusca;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCargoAtual;
    private javax.swing.JLabel jLabelCargoAtualFunc;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelCpfFunc;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeFunc;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JRadioButton jRadioButtonCpf;
    private javax.swing.JRadioButton jRadioButtonId;
    // End of variables declaration//GEN-END:variables
}
