/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.telasFuncionario;
import view.TelaEscolhaModulo;

/**
 *
 * @author Mario
 */
public class TelaMenuFuncionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuFuncionario.class.getName());

    /**
     * Creates new form TelaMenuFuncionario
     */
    public TelaMenuFuncionario() {
        initComponents();
        
        // 1. Maximiza a janela
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        // =================================================================
        // CENTRALIZAÇÃO HORIZONTAL DO MENU LATERAL (jPanelMenu1)
        // =================================================================
        jPanelMenu1.setLayout(new javax.swing.BoxLayout(jPanelMenu1, javax.swing.BoxLayout.Y_AXIS));

        float centroX = java.awt.Component.CENTER_ALIGNMENT;

        // --- DEFINE UMA LARGURA PADRÃO PARA TODOS OS BOTÕES ---
        // 140 pixels de largura por 30 pixels de altura (ajuste como preferir)
        java.awt.Dimension tamanhoBotao = new java.awt.Dimension(140, 30);

        jButtonCadastrarFunc.setMaximumSize(tamanhoBotao);
        jButtonAtualizarFunc.setMaximumSize(tamanhoBotao);
        jButtonConsultarFunc.setMaximumSize(tamanhoBotao);
        jButtonListarFunc.setMaximumSize(tamanhoBotao);
        jButtonContrataFunc.setMaximumSize(tamanhoBotao);
        jButtonCargoFunc.setMaximumSize(tamanhoBotao);
        jButtonSalarioFunc.setMaximumSize(tamanhoBotao);
        jButtonDesligarFunc.setMaximumSize(tamanhoBotao);
        jButtonAcessoFunc.setMaximumSize(tamanhoBotao);
        jButtonSairFunc.setMaximumSize(tamanhoBotao);
        // -----------------------------------------------------

        // Aplica o alinhamento horizontal no centro para cada componente
        jLabelMenu1.setAlignmentX(centroX);
        jButtonCadastrarFunc.setAlignmentX(centroX);
        jButtonAtualizarFunc.setAlignmentX(centroX);
        jButtonConsultarFunc.setAlignmentX(centroX);
        jButtonListarFunc.setAlignmentX(centroX);
        jButtonContrataFunc.setAlignmentX(centroX);
        jButtonCargoFunc.setAlignmentX(centroX);
        jButtonSalarioFunc.setAlignmentX(centroX);
        jButtonDesligarFunc.setAlignmentX(centroX);
        jButtonAcessoFunc.setAlignmentX(centroX);
        jButtonSairFunc.setAlignmentX(centroX);

        // Reconstrói o menu adicionando pequenos espaçamentos verticais entre eles
        jPanelMenu1.removeAll();
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jLabelMenu1);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonCadastrarFunc);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonAtualizarFunc);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonConsultarFunc);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonListarFunc);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonContrataFunc);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonCargoFunc);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonSalarioFunc);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonDesligarFunc);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonAcessoFunc);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonSairFunc);

        // =================================================================
        // CENTRALIZAÇÃO HORIZONTAL DA ÁREA DE CONTEÚDO (jPanelTela)
        // =================================================================
        // Mesma lógica: empilha de cima para baixo, centralizado na horizontal
        jPanelTela.setLayout(new javax.swing.BoxLayout(jPanelTela, javax.swing.BoxLayout.Y_AXIS));

        jLabelBemVindoFunc.setAlignmentX(centroX);

        jPanelTela.removeAll();
        jPanelTela.add(javax.swing.Box.createVerticalStrut(20)); // Margem do topo da tela
        jPanelTela.add(jLabelBemVindoFunc);

        // Força a atualização do layout
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMenu1 = new javax.swing.JPanel();
        jLabelMenu1 = new javax.swing.JLabel();
        jButtonCadastrarFunc = new javax.swing.JButton();
        jButtonAtualizarFunc = new javax.swing.JButton();
        jButtonConsultarFunc = new javax.swing.JButton();
        jButtonListarFunc = new javax.swing.JButton();
        jButtonSairFunc = new javax.swing.JButton();
        jButtonContrataFunc = new javax.swing.JButton();
        jButtonCargoFunc = new javax.swing.JButton();
        jButtonSalarioFunc = new javax.swing.JButton();
        jButtonDesligarFunc = new javax.swing.JButton();
        jButtonAcessoFunc = new javax.swing.JButton();
        jPanelTela = new javax.swing.JPanel();
        jLabelBemVindoFunc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelMenu1.setBackground(new java.awt.Color(102, 102, 255));

        jLabelMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu1.setText("MENU");

        jButtonCadastrarFunc.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCadastrarFunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastrarFunc.setText("Cadastrar");
        jButtonCadastrarFunc.addActionListener(this::jButtonCadastrarFuncActionPerformed);

        jButtonAtualizarFunc.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAtualizarFunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtualizarFunc.setText("Atualizar");
        jButtonAtualizarFunc.addActionListener(this::jButtonAtualizarFuncActionPerformed);

        jButtonConsultarFunc.setBackground(new java.awt.Color(51, 51, 51));
        jButtonConsultarFunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarFunc.setText("Consultar");
        jButtonConsultarFunc.addActionListener(this::jButtonConsultarFuncActionPerformed);

        jButtonListarFunc.setBackground(new java.awt.Color(51, 51, 51));
        jButtonListarFunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListarFunc.setText("Listar");
        jButtonListarFunc.addActionListener(this::jButtonListarFuncActionPerformed);

        jButtonSairFunc.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSairFunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSairFunc.setText("Sair");
        jButtonSairFunc.addActionListener(this::jButtonSairFuncActionPerformed);

        jButtonContrataFunc.setBackground(new java.awt.Color(51, 51, 51));
        jButtonContrataFunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonContrataFunc.setText("Contratar");
        jButtonContrataFunc.addActionListener(this::jButtonContrataFuncActionPerformed);

        jButtonCargoFunc.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCargoFunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCargoFunc.setText("Cargo");
        jButtonCargoFunc.addActionListener(this::jButtonCargoFuncActionPerformed);

        jButtonSalarioFunc.setBackground(new java.awt.Color(51, 51, 51));
        jButtonSalarioFunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalarioFunc.setText("Salário");
        jButtonSalarioFunc.addActionListener(this::jButtonSalarioFuncActionPerformed);

        jButtonDesligarFunc.setBackground(new java.awt.Color(51, 51, 51));
        jButtonDesligarFunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDesligarFunc.setText("Desligar");
        jButtonDesligarFunc.addActionListener(this::jButtonDesligarFuncActionPerformed);

        jButtonAcessoFunc.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAcessoFunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAcessoFunc.setText("Acesso");
        jButtonAcessoFunc.addActionListener(this::jButtonAcessoFuncActionPerformed);

        javax.swing.GroupLayout jPanelMenu1Layout = new javax.swing.GroupLayout(jPanelMenu1);
        jPanelMenu1.setLayout(jPanelMenu1Layout);
        jPanelMenu1Layout.setHorizontalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAcessoFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDesligarFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalarioFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCargoFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonContrataFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastrarFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConsultarFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAtualizarFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListarFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSairFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        jPanelMenu1Layout.setVerticalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenu1)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastrarFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAtualizarFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultarFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListarFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContrataFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCargoFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalarioFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDesligarFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAcessoFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSairFunc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelMenu1, java.awt.BorderLayout.LINE_START);

        jPanelTela.setBackground(new java.awt.Color(153, 153, 255));

        jLabelBemVindoFunc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelBemVindoFunc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBemVindoFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBemVindoFunc.setText("Bem vindo ao módulo Funcionários");

        javax.swing.GroupLayout jPanelTelaLayout = new javax.swing.GroupLayout(jPanelTela);
        jPanelTela.setLayout(jPanelTelaLayout);
        jPanelTelaLayout.setHorizontalGroup(
            jPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBemVindoFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );
        jPanelTelaLayout.setVerticalGroup(
            jPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBemVindoFunc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelTela, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarFuncActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout do jPanelTela para GridBagLayout (ele vai garantir a centralização)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de cadastro normalmente
        TelaCadastroFuncionario telaCadastro = new TelaCadastroFuncionario();

        // 4. Cria um painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaCadastro.getBackground()); // Mantém a cor azul de fundo

        // Define o tamanho máximo desejado (450px de largura por 420px de altura)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 420);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);

        // 5. Adiciona a tela de cadastro para preencher esse limitador
        limitadorLargura.add(telaCadastro, java.awt.BorderLayout.CENTER);

        // 6. Configura o GridBagLayout para fixar o limitador morto no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical

        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);

        // 7. Atualiza e renderiza os novos componentes na interface
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonCadastrarFuncActionPerformed

    private void jButtonAtualizarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarFuncActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout do jPanelTela para GridBagLayout (garante a centralização)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de atualização 
        TelaAtualizarFuncionarios telaAtualizar = new TelaAtualizarFuncionarios();

        // 4. Cria um painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaAtualizar.getBackground()); // Mantém a cor de fundo padrão da tela

        // Define o tamanho máximo desejado (mesmo padrão de 450px por 420px usado no cadastro)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 500);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);

        // 5. Adiciona a tela de atualização para preencher esse limitador
        limitadorLargura.add(telaAtualizar, java.awt.BorderLayout.CENTER);

        // 6. Configura o GridBagLayout para fixar o limitador morto no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical

        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);

        // 7. Atualiza e renderiza os novos componentes na interface
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonAtualizarFuncActionPerformed

    private void jButtonConsultarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarFuncActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout para GridBagLayout (ele gerencia o alinhamento centralizado perfeitamente)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de consulta normalmente
        TelaConsultaFuncionario telaConsulta = new TelaConsultaFuncionario();
        
        telaConsulta.popularTabelaFuncionarios();

        // 4. Configura as regras de posicionamento do GridBagLayout
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;

        // ATENÇÃO AQUI: Força o painel de consulta a ocupar toda a largura disponível (100%)
        // mas mantém o ponto de ancoragem centralizado horizontalmente.
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = java.awt.GridBagConstraints.BOTH; // Permite que a tabela cresça para os lados e para baixo
        gbc.anchor = java.awt.GridBagConstraints.CENTER;

        // Adiciona uma margem de respiro nas laterais e no topo (20 pixels)
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);

        // 5. Adiciona a tela configurada ao painel principal
        jPanelTela.add(telaConsulta, gbc);

        // 6. Atualiza e renderiza a interface na tela
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonConsultarFuncActionPerformed

    private void jButtonListarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarFuncActionPerformed
        // 1. Limpa a área de conteúdo atual
        jPanelTela.removeAll();

        // 2. Define o layout como BorderLayout para a tabela expandir e ocupar o espaço útil da direita
        jPanelTela.setLayout(new java.awt.BorderLayout());

        // 3. Instancia a tela de listagem que criamos
        TelaListarFuncionarios telaListar = new TelaListarFuncionarios();
        
        // CORREÇÃO AQUI: Força a tabela a reler os dados novos do repositório antes de desenhar
        telaListar.carregarTabela();

        // 4. Adiciona ao centro do painel com uma pequena borda de respiro (margem nas laterais)
        telaListar.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanelTela.add(telaListar, java.awt.BorderLayout.CENTER);

        // 5. Atualiza e redesenha a tela
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonListarFuncActionPerformed

    private void jButtonSairFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairFuncActionPerformed
        // 1. Instancia a tela de escolha de módulos
        TelaEscolhaModulo telaModulo = new TelaEscolhaModulo();

        // 2. Torna a nova janela visível
        telaModulo.setVisible(true);

        // 3. Centraliza a nova janela no meio do ecrã/monitor
        telaModulo.setLocationRelativeTo(null);

        // 4. Fecha e destrói o JFrame atual do Menu do Funcionario
        this.dispose();
    }//GEN-LAST:event_jButtonSairFuncActionPerformed

    private void jButtonSalarioFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalarioFuncActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout do jPanelTela para GridBagLayout (garante a centralização perfeita)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de contratação que finalizamos
        TelaSalarioFuncionario telaSalario = new TelaSalarioFuncionario();

        // 4. Cria o painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaSalario.getBackground()); // Mantém a cor azul/roxa de fundo

        // Define o tamanho máximo desejado (com base nos campos dela, 450px por 500px fica excelente)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 500);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);

        // 5. Adiciona a tela de contratação para preencher esse limitador
        limitadorLargura.add(telaSalario, java.awt.BorderLayout.CENTER);

        // 6. Configura o GridBagLayout para fixar o limitador bem no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical

        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);

        // 7. Força o Java a atualizar e renderizar a interface com a nova tela interna
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonSalarioFuncActionPerformed

    private void jButtonContrataFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContrataFuncActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout do jPanelTela para GridBagLayout (garante a centralização perfeita)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de contratação que finalizamos
        TelaContrataFuncionario telaContratar = new TelaContrataFuncionario();

        // 4. Cria o painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaContratar.getBackground()); // Mantém a cor azul/roxa de fundo

        // Define o tamanho máximo desejado (com base nos campos dela, 450px por 500px fica excelente)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 500);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);

        // 5. Adiciona a tela de contratação para preencher esse limitador
        limitadorLargura.add(telaContratar, java.awt.BorderLayout.CENTER);

        // 6. Configura o GridBagLayout para fixar o limitador bem no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical

        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);

        // 7. Força o Java a atualizar e renderizar a interface com a nova tela interna
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonContrataFuncActionPerformed

    private void jButtonCargoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargoFuncActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout do jPanelTela para GridBagLayout (garante a centralização perfeita)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de contratação que finalizamos
        TelaCargoFuncionario telaCargo = new TelaCargoFuncionario();

        // 4. Cria o painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaCargo.getBackground()); // Mantém a cor azul/roxa de fundo

        // Define o tamanho máximo desejado (com base nos campos dela, 450px por 500px fica excelente)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 500);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);

        // 5. Adiciona a tela de contratação para preencher esse limitador
        limitadorLargura.add(telaCargo, java.awt.BorderLayout.CENTER);

        // 6. Configura o GridBagLayout para fixar o limitador bem no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical

        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);

        // 7. Força o Java a atualizar e renderizar a interface com a nova tela interna
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonCargoFuncActionPerformed

    private void jButtonDesligarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesligarFuncActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout do jPanelTela para GridBagLayout (garante a centralização perfeita)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de contratação que finalizamos
        TelaDesligaFuncionario telaDesligamento = new TelaDesligaFuncionario();

        // 4. Cria o painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaDesligamento.getBackground()); // Mantém a cor azul/roxa de fundo

        // Define o tamanho máximo desejado (com base nos campos dela, 450px por 500px fica excelente)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 500);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);

        // 5. Adiciona a tela de contratação para preencher esse limitador
        limitadorLargura.add(telaDesligamento, java.awt.BorderLayout.CENTER);

        // 6. Configura o GridBagLayout para fixar o limitador bem no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical

        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);

        // 7. Força o Java a atualizar e renderizar a interface com a nova tela interna
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonDesligarFuncActionPerformed

    private void jButtonAcessoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessoFuncActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout do jPanelTela para GridBagLayout (garante a centralização perfeita)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de contratação que finalizamos
        TelaAtualizaAcesso telaAcesso = new TelaAtualizaAcesso();

        // 4. Cria o painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaAcesso.getBackground()); // Mantém a cor azul/roxa de fundo

        // Define o tamanho máximo desejado (com base nos campos dela, 450px por 500px fica excelente)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 500);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);

        // 5. Adiciona a tela de contratação para preencher esse limitador
        limitadorLargura.add(telaAcesso, java.awt.BorderLayout.CENTER);

        // 6. Configura o GridBagLayout para fixar o limitador bem no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical

        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);

        // 7. Força o Java a atualizar e renderizar a interface com a nova tela interna
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonAcessoFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenuFuncionario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessoFunc;
    private javax.swing.JButton jButtonAtualizarFunc;
    private javax.swing.JButton jButtonCadastrarFunc;
    private javax.swing.JButton jButtonCargoFunc;
    private javax.swing.JButton jButtonConsultarFunc;
    private javax.swing.JButton jButtonContrataFunc;
    private javax.swing.JButton jButtonDesligarFunc;
    private javax.swing.JButton jButtonListarFunc;
    private javax.swing.JButton jButtonSairFunc;
    private javax.swing.JButton jButtonSalarioFunc;
    private javax.swing.JLabel jLabelBemVindoFunc;
    private javax.swing.JLabel jLabelMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenu1;
    private javax.swing.JPanel jPanelTela;
    // End of variables declaration//GEN-END:variables
}
