/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.telasEstoque;

import controladores.ControladorProduto;
import java.text.DecimalFormat;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Mario
 */
public class TelaAlterarEstoque extends javax.swing.JPanel {
    
    private entidades.Produto produtoAtual;
    private boolean escutadorAtivo = false;

    /**
     * Creates new form TelaAlterarEstoque
     */
    public TelaAlterarEstoque() {
        initComponents();
        
        // Configuração do spinner (ID do produto)
        jSpinnerIdProduto.setModel(new javax.swing.SpinnerNumberModel(
                0, // valor inicial
                0, // valor mínimo
                null, // valor máximo (sem limite)
                1 // incremento
        ));
        
        //MASCARA DE QUANTIDADE
        DecimalFormat formatoNumero = new DecimalFormat("0.00");

        NumberFormatter formatter = new NumberFormatter(formatoNumero);
        formatter.setValueClass(Double.class);
        formatter.setAllowsInvalid(false);
        formatter.setOverwriteMode(true);
        jFormattedTextFieldQuantidadeAlterada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatter));

        // Define um valor inicial numérico para evitar erros de inicialização vazia
        jFormattedTextFieldQuantidadeAlterada.setValue(0.00);
        
        // --- SEU CÓDIGO EDITÁVEL COMEÇA AQUI ---
        configurarEscutadoresDeModificacao();

        // O botão de atualizar inicia desativado até que alguma modificação ocorra
        jButtonAlterarEstoque.setEnabled(false);
    }
    
    // Monitora se o usuário alterar qualquer dado após a busca
    private void configurarEscutadoresDeModificacao() {
        DocumentListener dl = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                verificarAlteracao();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                verificarAlteracao();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                verificarAlteracao();
            }
        };

        jFormattedTextFieldQuantidadeAlterada.getDocument().addDocumentListener(dl);
        
    }

    private void verificarAlteracao() {
        if (escutadorAtivo && produtoAtual != null) {
            jButtonAlterarEstoque.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelPrecoCompra = new javax.swing.JLabel();
        jLabel1TelefoneCli = new javax.swing.JLabel();
        jButtonAlterarEstoque = new javax.swing.JButton();
        jLabelIdFornecedor = new javax.swing.JLabel();
        jLabelIdIdProduto = new javax.swing.JLabel();
        jSpinnerIdProduto = new javax.swing.JSpinner();
        jButtonBuscar = new javax.swing.JButton();
        jLabelValorIdFornecedor = new javax.swing.JLabel();
        jLabelValorNomeProduto = new javax.swing.JLabel();
        jLabelValorDescricao = new javax.swing.JLabel();
        jLabelValorPrecoCompra = new javax.swing.JLabel();
        jLabelValorQuantidadeEstoque = new javax.swing.JLabel();
        jLabelQuantidadeAlterada = new javax.swing.JLabel();
        jFormattedTextFieldQuantidadeAlterada = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(153, 153, 255));
        setForeground(new java.awt.Color(0, 0, 0));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("ATUALIZAR ESTOQUE");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNome.setText("Nome");

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDescricao.setText("Descrição");

        jLabelPrecoCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPrecoCompra.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecoCompra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrecoCompra.setText("<html><div style='text-align:right;'>Preço<br>compra</div></html>");

        jLabel1TelefoneCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1TelefoneCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1TelefoneCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1TelefoneCli.setText("<html><div style='text-align:right;'>Quantidade<br>estoque</div></html>");

        jButtonAlterarEstoque.setBackground(new java.awt.Color(102, 102, 255));
        jButtonAlterarEstoque.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAlterarEstoque.setText("Alterar estoque");
        jButtonAlterarEstoque.addActionListener(this::jButtonAlterarEstoqueActionPerformed);

        jLabelIdFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIdFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIdFornecedor.setText("ID Fornecedor");

        jLabelIdIdProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIdIdProduto.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdIdProduto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIdIdProduto.setText("ID Produto");

        jButtonBuscar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(this::jButtonBuscarActionPerformed);

        jLabelValorIdFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelValorIdFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorIdFornecedor.setText("            ");

        jLabelValorNomeProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelValorNomeProduto.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorNomeProduto.setText("            ");

        jLabelValorDescricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelValorDescricao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorDescricao.setText("            ");

        jLabelValorPrecoCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelValorPrecoCompra.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorPrecoCompra.setText("            ");

        jLabelValorQuantidadeEstoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelValorQuantidadeEstoque.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorQuantidadeEstoque.setText("            ");

        jLabelQuantidadeAlterada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelQuantidadeAlterada.setForeground(new java.awt.Color(0, 0, 0));
        jLabelQuantidadeAlterada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelQuantidadeAlterada.setText("<html><div style='text-align:right;'>Quantidade<br>alterada</div></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelIdIdProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelIdFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpinnerIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBuscar))
                                    .addComponent(jLabelValorIdFornecedor)
                                    .addComponent(jLabelValorNomeProduto)
                                    .addComponent(jLabelValorDescricao)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelPrecoCompra)
                                    .addComponent(jLabel1TelefoneCli, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelValorPrecoCompra)
                                    .addComponent(jLabelValorQuantidadeEstoque)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButtonAlterarEstoque))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelQuantidadeAlterada, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldQuantidadeAlterada, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdIdProduto)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdFornecedor)
                    .addComponent(jLabelValorIdFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelValorNomeProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescricao)
                    .addComponent(jLabelValorDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelValorPrecoCompra)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1TelefoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelValorQuantidadeEstoque)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelQuantidadeAlterada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldQuantidadeAlterada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addComponent(jButtonAlterarEstoque)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarEstoqueActionPerformed
        // RECUPERA QUANTIDADE ESTOQUE
        double quantidadeAteraEstoque = 0.0;
        if (jFormattedTextFieldQuantidadeAlterada.getValue() != null) {
            quantidadeAteraEstoque = ((Number) jFormattedTextFieldQuantidadeAlterada.getValue()).doubleValue();
        }

        // =================================================================
        // VALIDAÇÃO: VERIFICAÇÃO DE CAMPOS VAZIOS
        // =================================================================
        if (quantidadeAteraEstoque == 0) {

            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, o valor deve ser diferente de 0!",
                "Valor nulo",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Interrompe a execução aqui se faltar algo
        }

        // 1. Envia os dados para salvar
        controladores.ControladorEstoque.getInstanciaControladorEstoque().alteraEstoqueProduto(produtoAtual, quantidadeAteraEstoque);

        // =================================================================
        // NOVOS COMPORTAMENTOS: AVISO
        // =================================================================
        // 2. Mostra a caixinha de aviso de Sucesso
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Estoque atualizado com sucesso!",
            "Sucesso",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        jSpinnerIdProduto.requestFocus();

        // Desabilita de novo até a próxima alteração
        jButtonAlterarEstoque.setEnabled(false);
    }//GEN-LAST:event_jButtonAlterarEstoqueActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        int idProduto = (Integer) jSpinnerIdProduto.getValue();

        if (idProduto<=0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite o ID do produto para buscar.", "Campo Vazio", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Faz a chamada ao Controlador que configuramos anteriormente
        produtoAtual = ControladorProduto.getInstanciaControladorProduto().buscarProdutos(idProduto);

        if (produtoAtual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Produto não encontrado no sistema.", "Não Localizado", javax.swing.JOptionPane.ERROR_MESSAGE);
            jButtonAlterarEstoque.setEnabled(false);
            return;
        }

        jLabelValorNomeProduto.setText(produtoAtual.getNome());
        jLabelValorIdFornecedor.setText(String.valueOf(produtoAtual.getIdFornecedor()));
        jLabelValorDescricao.setText(produtoAtual.getDescricao());
        jLabelValorPrecoCompra.setText("R$ " + String.valueOf(produtoAtual.getPrecoCompra()));
        jLabelValorQuantidadeEstoque.setText(String.valueOf(produtoAtual.getQuantidadeEstoque()));

        // LibejLabelValorIdFornecedorcutador. Qualquer modificação que o usuário fizer a partir de agora ativará o botão "Atualizar"
        escutadorAtivo = true;
        jButtonAlterarEstoque.setEnabled(false);
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarEstoque;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JFormattedTextField jFormattedTextFieldQuantidadeAlterada;
    private javax.swing.JLabel jLabel1TelefoneCli;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelIdFornecedor;
    private javax.swing.JLabel jLabelIdIdProduto;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPrecoCompra;
    private javax.swing.JLabel jLabelQuantidadeAlterada;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelValorDescricao;
    private javax.swing.JLabel jLabelValorIdFornecedor;
    private javax.swing.JLabel jLabelValorNomeProduto;
    private javax.swing.JLabel jLabelValorPrecoCompra;
    private javax.swing.JLabel jLabelValorQuantidadeEstoque;
    private javax.swing.JSpinner jSpinnerIdProduto;
    // End of variables declaration//GEN-END:variables
}
