/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.telasEstoque;

import view.telasProduto.TelaConsultarProdutos;
import view.telasProduto.TelaListarProdutos;
import view.TelaEscolhaModulo;

/**
 *
 * @author Mario
 */
public class TelaMenuEstoque extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuEstoque.class.getName());

    /**
     * Creates new form TelaMenuEstoque
     */
    public TelaMenuEstoque() {
        initComponents();
        
        // 1. Maximiza a janela
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        // =================================================================
        // CENTRALIZAÇÃO HORIZONTAL DO MENU LATERAL (jPanelMenu1)
        // =================================================================
        jPanelMenu1.setLayout(new javax.swing.BoxLayout(jPanelMenu1, javax.swing.BoxLayout.Y_AXIS));

        float centroX = java.awt.Component.CENTER_ALIGNMENT;

        // --- DEFINE UMA LARGURA PADRÃO PARA TODOS OS BOTÕES ---
        // 140 pixels de largura por 30 pixels de altura (ajuste como preferir)
        java.awt.Dimension tamanhoBotao = new java.awt.Dimension(140, 37);

        jButtonAlterarEstoque.setMaximumSize(tamanhoBotao);
        jButtonAvisosEstoque.setMaximumSize(tamanhoBotao);
        jButtonConsultarEstoque.setMaximumSize(tamanhoBotao);
        jButtonListarEstoque.setMaximumSize(tamanhoBotao);
        jButtonSair.setMaximumSize(tamanhoBotao);
        // -----------------------------------------------------

        // Aplica o alinhamento horizontal no centro para cada componente
        jLabelMenu1.setAlignmentX(centroX);
        jButtonAlterarEstoque.setAlignmentX(centroX);
        jButtonAvisosEstoque.setAlignmentX(centroX);
        jButtonConsultarEstoque.setAlignmentX(centroX);
        jButtonListarEstoque.setAlignmentX(centroX);
        jButtonSair.setAlignmentX(centroX);

        // Reconstrói o menu adicionando pequenos espaçamentos verticais entre eles
        jPanelMenu1.removeAll();
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jLabelMenu1);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonAlterarEstoque);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonAvisosEstoque);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonConsultarEstoque);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonListarEstoque);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonSair);

        // =================================================================
        // CENTRALIZAÇÃO HORIZONTAL DA ÁREA DE CONTEÚDO (jPanelTela)
        // =================================================================
        // Mesma lógica: empilha de cima para baixo, centralizado na horizontal
        jPanelTela.setLayout(new javax.swing.BoxLayout(jPanelTela, javax.swing.BoxLayout.Y_AXIS));

        jLabelBemVindo.setAlignmentX(centroX);

        jPanelTela.removeAll();
        jPanelTela.add(javax.swing.Box.createVerticalStrut(20)); // Margem do topo da tela
        jPanelTela.add(jLabelBemVindo);

        // Força a atualização do layout
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMenu1 = new javax.swing.JPanel();
        jLabelMenu1 = new javax.swing.JLabel();
        jButtonAlterarEstoque = new javax.swing.JButton();
        jButtonAvisosEstoque = new javax.swing.JButton();
        jButtonConsultarEstoque = new javax.swing.JButton();
        jButtonListarEstoque = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanelTela = new javax.swing.JPanel();
        jLabelBemVindo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelMenu1.setBackground(new java.awt.Color(102, 102, 255));

        jLabelMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu1.setText("MENU");

        jButtonAlterarEstoque.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAlterarEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAlterarEstoque.setText("<html><center>Alterar<br>Estoque</center></html>");
        jButtonAlterarEstoque.addActionListener(this::jButtonAlterarEstoqueActionPerformed);

        jButtonAvisosEstoque.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAvisosEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAvisosEstoque.setText("<html><center>Avisos de<br>Estoque</center></html>");
        jButtonAvisosEstoque.addActionListener(this::jButtonAvisosEstoqueActionPerformed);

        jButtonConsultarEstoque.setBackground(new java.awt.Color(51, 51, 51));
        jButtonConsultarEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarEstoque.setText("<html><center>Consultar<br>Estoque</center></html>");
        jButtonConsultarEstoque.addActionListener(this::jButtonConsultarEstoqueActionPerformed);

        jButtonListarEstoque.setBackground(new java.awt.Color(51, 51, 51));
        jButtonListarEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListarEstoque.setText("<html><center>Listar<br>Estoque</center></html>");
        jButtonListarEstoque.addActionListener(this::jButtonListarEstoqueActionPerformed);

        jButtonSair.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(this::jButtonSairActionPerformed);

        javax.swing.GroupLayout jPanelMenu1Layout = new javax.swing.GroupLayout(jPanelMenu1);
        jPanelMenu1.setLayout(jPanelMenu1Layout);
        jPanelMenu1Layout.setHorizontalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAlterarEstoque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jButtonConsultarEstoque, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAvisosEstoque, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListarEstoque, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        jPanelMenu1Layout.setVerticalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlterarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAvisosEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelMenu1, java.awt.BorderLayout.LINE_START);

        jPanelTela.setBackground(new java.awt.Color(153, 153, 255));

        jLabelBemVindo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelBemVindo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBemVindo.setText("Bem vindo ao módulo Estoque");

        javax.swing.GroupLayout jPanelTelaLayout = new javax.swing.GroupLayout(jPanelTela);
        jPanelTela.setLayout(jPanelTelaLayout);
        jPanelTelaLayout.setHorizontalGroup(
            jPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );
        jPanelTelaLayout.setVerticalGroup(
            jPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBemVindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelTela, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarEstoqueActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout do jPanelTela para GridBagLayout (ele vai garantir a centralização)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de cadastro normalmente
        TelaAlterarEstoque telaCadastro = new TelaAlterarEstoque();

        // 4. Cria um painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaCadastro.getBackground()); // Mantém a cor azul de fundo

        // Define o tamanho máximo desejado (450px de largura por 420px de altura)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 420);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);

        // 5. Adiciona a tela de cadastro para preencher esse limitador
        limitadorLargura.add(telaCadastro, java.awt.BorderLayout.CENTER);

        // 6. Configura o GridBagLayout para fixar o limitador morto no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical

        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);

        // 7. Atualiza e renderiza os novos componentes na interface
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonAlterarEstoqueActionPerformed

    private void jButtonAvisosEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvisosEstoqueActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout para GridBagLayout (ele gerencia o alinhamento centralizado perfeitamente)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de consulta normalmente
        TelaAvisosEstoque telaConsulta = new TelaAvisosEstoque();
        
        telaConsulta.popularTabelaProdutos();

        // 4. Configura as regras de posicionamento do GridBagLayout
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;

        // ATENÇÃO AQUI: Força o painel de consulta a ocupar toda a largura disponível (100%)
        // mas mantém o ponto de ancoragem centralizado horizontalmente.
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = java.awt.GridBagConstraints.BOTH; // Permite que a tabela cresça para os lados e para baixo
        gbc.anchor = java.awt.GridBagConstraints.CENTER;

        // Adiciona uma margem de respiro nas laterais e no topo (20 pixels)
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);

        // 5. Adiciona a tela configurada ao painel principal
        jPanelTela.add(telaConsulta, gbc);

        // 6. Atualiza e renderiza a interface na tela
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonAvisosEstoqueActionPerformed

    private void jButtonConsultarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarEstoqueActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout para GridBagLayout (ele gerencia o alinhamento centralizado perfeitamente)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de consulta normalmente
        TelaConsultarProdutos telaConsulta = new TelaConsultarProdutos();
        
        telaConsulta.popularTabelaProdutos();

        // 4. Configura as regras de posicionamento do GridBagLayout
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;

        // ATENÇÃO AQUI: Força o painel de consulta a ocupar toda a largura disponível (100%)
        // mas mantém o ponto de ancoragem centralizado horizontalmente.
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = java.awt.GridBagConstraints.BOTH; // Permite que a tabela cresça para os lados e para baixo
        gbc.anchor = java.awt.GridBagConstraints.CENTER;

        // Adiciona uma margem de respiro nas laterais e no topo (20 pixels)
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);

        // 5. Adiciona a tela configurada ao painel principal
        jPanelTela.add(telaConsulta, gbc);

        // 6. Atualiza e renderiza a interface na tela
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonConsultarEstoqueActionPerformed

    private void jButtonListarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarEstoqueActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();

        // 2. Define o layout para GridBagLayout (ele gerencia o alinhamento centralizado perfeitamente)
        jPanelTela.setLayout(new java.awt.GridBagLayout());

        // 3. Instancia a tela de consulta normalmente
        TelaListarProdutos telaListar = new TelaListarProdutos();
        
        telaListar.carregarTabela();

        // 4. Configura as regras de posicionamento do GridBagLayout
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;

        // ATENÇÃO AQUI: Força o painel de consulta a ocupar toda a largura disponível (100%)
        // mas mantém o ponto de ancoragem centralizado horizontalmente.
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = java.awt.GridBagConstraints.BOTH; // Permite que a tabela cresça para os lados e para baixo
        gbc.anchor = java.awt.GridBagConstraints.CENTER;

        // Adiciona uma margem de respiro nas laterais e no topo (20 pixels)
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);

        // 5. Adiciona a tela configurada ao painel principal
        jPanelTela.add(telaListar, gbc);

        // 6. Atualiza e renderiza a interface na tela
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonListarEstoqueActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // 1. Instancia a tela de escolha de módulos
        TelaEscolhaModulo telaModulo = new TelaEscolhaModulo();

        // 2. Torna a nova janela visível
        telaModulo.setVisible(true);

        // 3. Centraliza a nova janela no meio do ecrã/monitor
        telaModulo.setLocationRelativeTo(null);

        // 4. Fecha e destrói o JFrame atual do Menu do Funcionario
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenuEstoque().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarEstoque;
    private javax.swing.JButton jButtonAvisosEstoque;
    private javax.swing.JButton jButtonConsultarEstoque;
    private javax.swing.JButton jButtonListarEstoque;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JLabel jLabelMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenu1;
    private javax.swing.JPanel jPanelTela;
    // End of variables declaration//GEN-END:variables
}
