/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.telasProduto;

import java.text.DecimalFormat;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.NumberFormatter;
import controladores.ControladorProduto;

/**
 *
 * @author Mario
 */
public class TelaAtualizarProdutos extends javax.swing.JPanel {

    private entidades.Produto produtoAtual; // Armazena o funcionario localizado
    private boolean escutadorAtivo = false;  // Controla para não ativar o botão enquanto carrega os dados

    /**
     * Creates new form TelaAtualizarProdutos
     */
    public TelaAtualizarProdutos() {
        initComponents();
        
        // Configuração do spinner (ID do produto)
        jSpinnerIdProduto.setModel(new javax.swing.SpinnerNumberModel(
                0, // valor inicial
                0, // valor mínimo
                null, // valor máximo (sem limite)
                1 // incremento
        ));
        
        // Configuração do spinner (ID do fornecedor)
        jSpinnerIdFornecedor.setModel(new javax.swing.SpinnerNumberModel(
                0, // valor inicial
                0, // valor mínimo
                null, // valor máximo (sem limite)
                1 // incremento
        ));

        // --- SEU CÓDIGO EDITÁVEL COMEÇA AQUI ---
        configurarMascaras();
        configurarEscutadoresDeModificacao();

        // O botão de atualizar inicia desativado até que alguma modificação ocorra
        jButtonAtualizar.setEnabled(false);
    }

    private void configurarMascaras() {
        // =================================================================
        // FORMATADOR MONETÁRIO E DE QUANTIDADE
        // =================================================================
        java.text.NumberFormat formatoMoeda = java.text.NumberFormat.getCurrencyInstance();
        formatoMoeda.setMinimumFractionDigits(2);
        formatoMoeda.setMaximumFractionDigits(2);

        javax.swing.text.NumberFormatter formatterSalario = new javax.swing.text.NumberFormatter(formatoMoeda);
        formatterSalario.setAllowsInvalid(false); // Impede digitação de letras
        formatterSalario.setOverwriteMode(true);

        jFormattedTextFieldPrecoCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatterSalario));

        DecimalFormat formatoNumero = new DecimalFormat("0.00");

        NumberFormatter formatter = new NumberFormatter(formatoNumero);
        formatter.setValueClass(Double.class);
        formatter.setAllowsInvalid(false);
        formatter.setMinimum(0.0);
        formatter.setOverwriteMode(true);
        jFormattedTextFieldQuantidadeEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatter));

        // Define um valor inicial numérico para evitar erros de inicialização vazia
        jFormattedTextFieldPrecoCompra.setValue(0.00);
        jFormattedTextFieldQuantidadeEstoque.setValue(0.00);
    }

    // Monitora se o usuário alterar qualquer dado após a busca
    private void configurarEscutadoresDeModificacao() {
        DocumentListener dl = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                verificarAlteracao();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                verificarAlteracao();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                verificarAlteracao();
            }
        };

        jTextFieldNome.getDocument().addDocumentListener(dl);
        jTextAreaDescricao.getDocument().addDocumentListener(dl);
        jFormattedTextFieldPrecoCompra.getDocument().addDocumentListener(dl);
        jFormattedTextFieldQuantidadeEstoque.getDocument().addDocumentListener(dl);
        
        // Listener específico do spinner
        jSpinnerIdFornecedor.addChangeListener(e -> verificarAlteracao());
    }

    private void verificarAlteracao() {
        if (escutadorAtivo && produtoAtual != null) {
            jButtonAtualizar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelPrecoCompra = new javax.swing.JLabel();
        jLabel1TelefoneCli = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldPrecoCompra = new javax.swing.JFormattedTextField();
        jFormattedTextFieldQuantidadeEstoque = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jButtonAtualizar = new javax.swing.JButton();
        jLabelIdFornecedor = new javax.swing.JLabel();
        jSpinnerIdFornecedor = new javax.swing.JSpinner();
        jLabelIdIdProduto = new javax.swing.JLabel();
        jSpinnerIdProduto = new javax.swing.JSpinner();
        jButtonBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("ATUALIZAR PRODUTOS");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNome.setText("Nome");

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDescricao.setText("Descrição");

        jLabelPrecoCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPrecoCompra.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecoCompra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrecoCompra.setText("<html><div style='text-align:right;'>Preço<br>compra</div></html>");

        jLabel1TelefoneCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1TelefoneCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1TelefoneCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1TelefoneCli.setText("<html><div style='text-align:right;'>Quantidade<br>estoque</div></html>");

        jTextFieldNome.addActionListener(this::jTextFieldNomeActionPerformed);

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jButtonAtualizar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonAtualizar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(this::jButtonAtualizarActionPerformed);

        jLabelIdFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIdFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIdFornecedor.setText("ID Fornecedor");

        jLabelIdIdProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIdIdProduto.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdIdProduto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIdIdProduto.setText("ID Produto");

        jButtonBuscar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(this::jButtonBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelIdIdProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelIdFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpinnerIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBuscar)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPrecoCompra)
                            .addComponent(jLabel1TelefoneCli, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldPrecoCompra)
                            .addComponent(jFormattedTextFieldQuantidadeEstoque))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jButtonAtualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdIdProduto)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jFormattedTextFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addComponent(jLabelPrecoCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1TelefoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldQuantidadeEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAtualizar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        int idFornecedor = (Integer) jSpinnerIdFornecedor.getValue();
        String nome = jTextFieldNome.getText();
        String descricao = jTextAreaDescricao.getText();

        // RECUPERA PREÇO COMPRA
        double precoCompra = 0.0;
        if (jFormattedTextFieldPrecoCompra.getValue() != null) {
            precoCompra = ((Number) jFormattedTextFieldPrecoCompra.getValue()).doubleValue();
        }

        // RECUPERA QUANTIDADE ESTOQUE
        double quantidadeEstoque = 0.0;
        if (jFormattedTextFieldQuantidadeEstoque.getValue() != null) {
            quantidadeEstoque = ((Number) jFormattedTextFieldQuantidadeEstoque.getValue()).doubleValue();
        }

        // =================================================================
        // VALIDAÇÃO: VERIFICAÇÃO DE CAMPOS VAZIOS
        // =================================================================
        if (nome.isEmpty() || descricao.isEmpty() || precoCompra <= 0 || quantidadeEstoque <= 0) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, preencha todos os campos!",
                    "Campos Incompletos",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Interrompe a execução aqui se faltar algo
        }

        boolean existeFornecedor = controladores.ControladorFornecedor.getInstanciaControladorFornecedor().existeFornecedor(idFornecedor);

        if (!existeFornecedor) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "ID de fornecedor inexistente!",
                    "ID fornecedor inexistente",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Interrompe a execução
        }

        // 1. Envia os dados para salvar
        ControladorProduto.getInstanciaControladorProduto().atualizarProduto(produtoAtual.getIdProduto(), idFornecedor, nome, descricao, precoCompra, quantidadeEstoque);

        // =================================================================
        // NOVOS COMPORTAMENTOS: AVISO
        // =================================================================
        // 2. Mostra a caixinha de aviso de Sucesso
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Cadastro atualizado com sucesso!",
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        jSpinnerIdProduto.requestFocus();
        
        // Desabilita de novo até a próxima alteração
        jButtonAtualizar.setEnabled(false);
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        int idProduto = (Integer) jSpinnerIdProduto.getValue();

        if (idProduto<=0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite o ID do produto para buscar.", "Campo Vazio", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Faz a chamada ao Controlador que configuramos anteriormente
        produtoAtual = ControladorProduto.getInstanciaControladorProduto().buscarProdutos(idProduto);

        if (produtoAtual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Produto não encontrado no sistema.", "Não Localizado", javax.swing.JOptionPane.ERROR_MESSAGE);
            jButtonAtualizar.setEnabled(false);
            return;
        }

        // Bloqueia o escutador para não ativar o botão de "Atualizar" enquanto os dados entram nos campos
        escutadorAtivo = false;

        jTextFieldNome.setText(produtoAtual.getNome());
        jSpinnerIdFornecedor.setValue(produtoAtual.getIdFornecedor());
        jTextAreaDescricao.setText(produtoAtual.getDescricao());
        jFormattedTextFieldPrecoCompra.setValue(produtoAtual.getPrecoCompra());
        jFormattedTextFieldQuantidadeEstoque.setValue(produtoAtual.getQuantidadeEstoque());

        // Libera o escutador. Qualquer modificação que o usuário fizer a partir de agora ativará o botão "Atualizar"
        escutadorAtivo = true;
        jButtonAtualizar.setEnabled(false);
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecoCompra;
    private javax.swing.JFormattedTextField jFormattedTextFieldQuantidadeEstoque;
    private javax.swing.JLabel jLabel1TelefoneCli;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelIdFornecedor;
    private javax.swing.JLabel jLabelIdIdProduto;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPrecoCompra;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerIdFornecedor;
    private javax.swing.JSpinner jSpinnerIdProduto;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
