/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.telasProduto;

import java.text.DecimalFormat;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Mario
 */
public class TelaCadastrarProdutos extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastrarProdutos
     */
    public TelaCadastrarProdutos() {
        initComponents();

        // Configuração do spinner (ID do fornecedor)
        jSpinnerIdFornecedor.setModel(new javax.swing.SpinnerNumberModel(
                0, // valor inicial
                0, // valor mínimo
                null, // valor máximo (sem limite)
                1 // incremento
        ));

        // =================================================================
        // FORMATADOR MONETÁRIO E DE QUANTIDADE
        // =================================================================
        java.text.NumberFormat formatoMoeda = java.text.NumberFormat.getCurrencyInstance();
        formatoMoeda.setMinimumFractionDigits(2);
        formatoMoeda.setMaximumFractionDigits(2);

        javax.swing.text.NumberFormatter formatterSalario = new javax.swing.text.NumberFormatter(formatoMoeda);
        formatterSalario.setAllowsInvalid(false); // Impede digitação de letras
        formatterSalario.setOverwriteMode(true);

        jFormattedTextFieldPrecoCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatterSalario));

        DecimalFormat formatoNumero = new DecimalFormat("0.00");

        NumberFormatter formatter = new NumberFormatter(formatoNumero);
        formatter.setValueClass(Double.class);
        formatter.setAllowsInvalid(false);
        formatter.setMinimum(0.0);
        formatter.setOverwriteMode(true);
        jFormattedTextFieldQuantidadeEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatter));

        // Define um valor inicial numérico para evitar erros de inicialização vazia
        jFormattedTextFieldPrecoCompra.setValue(0.00);
        jFormattedTextFieldQuantidadeEstoque.setValue(0.00);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelPrecoCompra = new javax.swing.JLabel();
        jLabel1TelefoneCli = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldPrecoCompra = new javax.swing.JFormattedTextField();
        jFormattedTextFieldQuantidadeEstoque = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelIdFornecedor = new javax.swing.JLabel();
        jSpinnerIdFornecedor = new javax.swing.JSpinner();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(153, 153, 255));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("CADASTRAR PRODUTOS");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNome.setText("Nome");

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDescricao.setText("Descrição");

        jLabelPrecoCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPrecoCompra.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecoCompra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrecoCompra.setText("<html><div style='text-align:right;'>Preço<br>compra</div></html>");

        jLabel1TelefoneCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1TelefoneCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1TelefoneCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1TelefoneCli.setText("<html><div style='text-align:right;'>Quantidade<br>estoque</div></html>");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jButtonCadastrar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastrar.setText("Cadastrar produto");
        jButtonCadastrar.addActionListener(this::jButtonCadastrarActionPerformed);

        jLabelIdFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIdFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIdFornecedor.setText("ID Fornecedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelIdFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPrecoCompra, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1TelefoneCli, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldQuantidadeEstoque)
                    .addComponent(jFormattedTextFieldPrecoCompra)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadastrar)
                            .addComponent(jSpinnerIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdFornecedor)
                    .addComponent(jSpinnerIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1TelefoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldQuantidadeEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastrar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        int idFornecedor = (Integer) jSpinnerIdFornecedor.getValue();
        String nome = jTextFieldNome.getText();
        String descricao = jTextAreaDescricao.getText();

        // RECUPERA PREÇO COMPRA
        double precoCompra = 0.0;
        if (jFormattedTextFieldPrecoCompra.getValue() != null) {
            precoCompra = ((Number) jFormattedTextFieldPrecoCompra.getValue()).doubleValue();
        }

        // RECUPERA QUANTIDADE ESTOQUE
        double quantidadeEstoque = 0.0;
        if (jFormattedTextFieldQuantidadeEstoque.getValue() != null) {
            quantidadeEstoque = ((Number) jFormattedTextFieldQuantidadeEstoque.getValue()).doubleValue();
        }

        // =================================================================
        // VALIDAÇÃO: VERIFICAÇÃO DE CAMPOS VAZIOS
        // =================================================================
        if (nome.isEmpty() || descricao.isEmpty() || precoCompra <= 0 || quantidadeEstoque <= 0) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, preencha todos os campos!",
                    "Campos Incompletos",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Interrompe a execução aqui se faltar algo
        }

        boolean existeFornecedor = controladores.ControladorFornecedor.getInstanciaControladorFornecedor().existeFornecedor(idFornecedor);

        if (!existeFornecedor) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "ID de fornecedor inexistente!",
                    "ID fornecedor inexistente",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Interrompe a execução 
        }

        // 1. Envia os dados para salvar
        int idProduto = controladores.ControladorProduto.getInstanciaControladorProduto().cadastrarProduto(idFornecedor, nome, descricao, precoCompra, quantidadeEstoque);

        // =================================================================
        // NOVOS COMPORTAMENTOS: AVISO E LIMPEZA 
        // =================================================================
        // 2. Mostra a caixinha de aviso de Sucesso
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Produto '" + nome + "' cadastrado com sucesso no ID " + idProduto,
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        // 3. Limpa todos os campos da tela
        jSpinnerIdFornecedor.setValue(0);
        jTextFieldNome.setText("");
        jTextAreaDescricao.setText("");
        jFormattedTextFieldPrecoCompra.setValue(0.00);
        jFormattedTextFieldQuantidadeEstoque.setValue(0.00);

        jSpinnerIdFornecedor.requestFocus();

    }//GEN-LAST:event_jButtonCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecoCompra;
    private javax.swing.JFormattedTextField jFormattedTextFieldQuantidadeEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1TelefoneCli;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelIdFornecedor;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPrecoCompra;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerIdFornecedor;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
