/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.telasFornecedor;

/**
 *
 * @author Mario
 */
public class TelaListarFornecedor extends javax.swing.JPanel {

    /**
     * Creates new form TelaListarFornecedor
     */
    public TelaListarFornecedor() {
        initComponents();
        
        // 1. Remove as amarras do GroupLayout do NetBeans
        this.setLayout(new java.awt.BorderLayout());
        this.removeAll();
        
        // 2. Centraliza o texto do título e dá um espaçamento sutil (15px acima e abaixo)
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 0, 15, 0));
        
        // 3. Aplica uma margem sutil (respiro) nas laterais (10px) e embaixo (10px) do painel inteiro
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
        
        // 4. Injeta os componentes de volta de forma inteligente e responsiva
        this.add(jLabelTitulo, java.awt.BorderLayout.NORTH);   // O título fica preso no topo, centralizado
        this.add(jScrollPane1, java.awt.BorderLayout.CENTER);  // A tabela preenche TODO o espaço restante, expandindo junto com a tela
        
        // 5. Carrega os dados na tabela
        carregarTabela();
        
        // 6. Avisa o Java para recalcular as novas posições
        this.revalidate();
        this.repaint();
    }
    
    public void carregarTabela() {
        // 1. Pega a lista de funcionarios do seu repositório
        java.util.List<entidades.Fornecedor> lista = repositorio.Repositorio.getInstanciaRepositorio().getListaFornecedores();
        
        // 2. Captura o modelo da tabela para manipular as linhas
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTableListaFornecedores.getModel();
        
        // Limpa a tabela antes de carregar
        modelo.setNumRows(0);
        
        // 3. Varre a lista de funcionarios e adiciona cada um como uma nova linha
        for (entidades.Fornecedor fornec : lista) {
            modelo.addRow(new Object[]{
                fornec.getIdentificacao(),
                fornec.getNome(),
                fornec.getCpf(),
                fornec.getEmail(),
                fornec.getTelefone(),
                fornec.getEndereco().getLogradouro(),
                fornec.getEndereco().getNumero(),
                fornec.getEndereco().getBairro(),
                fornec.getEndereco().getCidade(),
                fornec.getEndereco().getEstado(),
                fornec.getEndereco().getCep(),
                fornec.getRepresentaEmpresaNome(),
                fornec.getRepresentaEmpresaCnpj()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaFornecedores = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("FORNECEDORES CADASTRADOS");

        jTableListaFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "E-mail", "Telefone", "Logradouro", "Número", "Bairro", "Cidade", "Estado", "CEP", "Razao Social", "CNPJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaFornecedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaFornecedores;
    // End of variables declaration//GEN-END:variables
}
