/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.telasFornecedor;

import controladores.ControladorFornecedor;

/**
 *
 * @author Mario
 */
public class TelaCadastrarFornecedor extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastrarFornecedor
     */
    public TelaCadastrarFornecedor() {
        initComponents();

        // MASCARAS DE FORMATAÇÃO
        try {
            // CPF
            javax.swing.text.MaskFormatter mascaraCpf = new javax.swing.text.MaskFormatter("###.###.###-##");
            mascaraCpf.setPlaceholderCharacter('_'); // Define o caractere de preenchimento
            jFormattedTextFieldCpf.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascaraCpf)
            );

            // Máscara para Telefone Celular (padrão de 9 dígitos + DDD)
            javax.swing.text.MaskFormatter mascaraTelefone = new javax.swing.text.MaskFormatter("(##) #####-####");
            mascaraTelefone.setPlaceholderCharacter('_');

            // Aplica ao seu componente JFormattedTextField do telefone
            jFormattedTextFieldTelefone.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascaraTelefone)
            );

            // CEP
            javax.swing.text.MaskFormatter mascaraCep = new javax.swing.text.MaskFormatter("#####-###");
            mascaraCep.setPlaceholderCharacter('_');
            jFormattedTextFieldCep.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascaraCep)
            );

            // CNPJ
            javax.swing.text.MaskFormatter mascaraCnpj = new javax.swing.text.MaskFormatter("##.###.###/####-##");
            mascaraCnpj.setPlaceholderCharacter('_');
            jFormattedTextFieldCnpj.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascaraCnpj)
            );

        } catch (java.text.ParseException ex) {
            // Trata um eventual erro de digitação na string da máscara ("###...")
            java.util.logging.Logger.getLogger(TelaCadastrarFornecedor.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabel1Telefone = new javax.swing.JLabel();
        jLabelLogradouro = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelCep = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabelRazaoSocial = new javax.swing.JLabel();
        jTextFieldRazaoSocial = new javax.swing.JTextField();
        jLabelCnpj = new javax.swing.JLabel();
        jFormattedTextFieldCnpj = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNome.setText("Nome");

        jLabelCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCpf.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCpf.setText("CPF");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEmail.setText("E-mail");

        jLabel1Telefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1Telefone.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1Telefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1Telefone.setText("Telefone");

        jLabelLogradouro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLogradouro.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLogradouro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLogradouro.setText("Logradouro");

        jLabelNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNumero.setText("Número");

        jLabelBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBairro.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBairro.setText("Bairro");

        jLabelCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCidade.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCidade.setText("Cidade");

        jLabelEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEstado.setText("Estado");

        jLabelCep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCep.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCep.setText("CEP");

        jTextFieldBairro.addActionListener(this::jTextFieldBairroActionPerformed);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("CADASTRO DE FORNECEDORES");

        jButtonCadastrar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(this::jButtonCadastrarActionPerformed);

        jLabelRazaoSocial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRazaoSocial.setForeground(new java.awt.Color(0, 0, 0));
        jLabelRazaoSocial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRazaoSocial.setText("Razão social");

        jLabelCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCnpj.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCnpj.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCnpj.setText("CNPJ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRazaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLogradouro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1Telefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNome)
                    .addComponent(jTextFieldEmail)
                    .addComponent(jTextFieldLogradouro)
                    .addComponent(jTextFieldNumero)
                    .addComponent(jTextFieldBairro)
                    .addComponent(jTextFieldCidade)
                    .addComponent(jFormattedTextFieldCpf)
                    .addComponent(jFormattedTextFieldCep)
                    .addComponent(jFormattedTextFieldTelefone)
                    .addComponent(jTextFieldRazaoSocial, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadastrar)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Telefone)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogradouro)
                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairro)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstado)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCep)
                    .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRazaoSocial)
                    .addComponent(jTextFieldRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCnpj)
                    .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadastrar)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        String nome = jTextFieldNome.getText().trim();
        String cpf = jFormattedTextFieldCpf.getText().trim();
        String email = jTextFieldEmail.getText().trim();
        String telefone = jFormattedTextFieldTelefone.getText().trim();
        String logradouro = jTextFieldLogradouro.getText().trim();
        String numero = jTextFieldNumero.getText().trim();
        String bairro = jTextFieldBairro.getText().trim();
        String cidade = jTextFieldCidade.getText().trim();
        String cep = jFormattedTextFieldCep.getText().trim();
        String razaoSocial = jTextFieldRazaoSocial.getText().trim();
        String cnpj = jFormattedTextFieldCnpj.getText().trim();

        // Pega o índice selecionado no ComboBox do Estado
        int estadoIndex = jComboBoxEstado.getSelectedIndex();

        // =================================================================
        // VALIDAÇÃO: VERIFICAÇÃO DE CAMPOS VAZIOS OU NÃO SELECIONADOS
        // =================================================================
        // Verifica se os campos de texto comuns estão vazios, se o combobox está no "-- Selecione --"
        // ou se os campos formatados contêm apenas os caracteres da máscara vazia.
        if (nome.isEmpty() || email.isEmpty() || logradouro.isEmpty() || numero.isEmpty()
                || bairro.isEmpty() || cidade.isEmpty() || estadoIndex == 0 || razaoSocial.isEmpty()
                || cpf.equals("___.___.___-__") || telefone.equals("(__) _____-____") || cep.equals("_____-___") || cnpj.equals("__.___.___/____-__")) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, preencha todos os campos obrigatórios e selecione o Estado!",
                    "Campos Incompletos",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Interrompe a execução aqui se faltar algo
        }

        // Expressão regular padrão para validar se o e-mail possui um formato válido
        String regexEmail = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        // Se o e-mail digitado não bater com o padrão, barra o cadastro
        if (!email.matches(regexEmail)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, insira um endereço de e-mail válido!",
                    "E-mail Inválido",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

            jTextFieldEmail.requestFocus();
            return;
        }

        // =================================================================
        // NOVA VALIDAÇÃO: VERIFICAÇÃO DE CPF DUPLICADO
        // =================================================================
        if (ControladorFornecedor.getInstanciaControladorFornecedor().cpfJaCadastradoFornecedor(cpf)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "O CPF informado (" + cpf + ") já está vinculado a um fornecedor cadastrado!",
                    "CPF Duplicado",
                    javax.swing.JOptionPane.WARNING_MESSAGE);

            jFormattedTextFieldCpf.requestFocus(); // Foca o cursor no campo do CPF
            return; // Interrompe o método AQUI. Nada abaixo é executado e os campos NÃO são limpos!
        }
        // =================================================================

        String estado = jComboBoxEstado.getSelectedItem().toString();

        // 1. Envia os dados para salvar
        int idFornecedor = ControladorFornecedor.getInstanciaControladorFornecedor().cadastrarFornecedorGrafico(nome, cpf, email, telefone, logradouro, numero, bairro, cidade, estado, cep, razaoSocial, cnpj);

        // =================================================================
        // NOVOS COMPORTAMENTOS: AVISO E LIMPEZA (Só roda se o CPF for inédito)
        // =================================================================
        // 2. Mostra a caixinha de aviso de Sucesso
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Fornecedor " + nome + " cadastrado com sucesso no ID " + idFornecedor,
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        // 3. Limpa todos os campos da tela
        jTextFieldNome.setText("");
        jFormattedTextFieldCpf.setValue(null);
        jTextFieldEmail.setText("");
        jFormattedTextFieldTelefone.setValue(null);
        jTextFieldLogradouro.setText("");
        jTextFieldNumero.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jComboBoxEstado.setSelectedIndex(0);
        jFormattedTextFieldCep.setValue(null);
        jTextFieldRazaoSocial.setText("");
        jFormattedTextFieldCnpj.setValue(null);

        // 4. Coloca o cursor piscando de volta no Nome do funcionario
        jTextFieldNome.requestFocus();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldCnpj;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1Telefone;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCnpj;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelRazaoSocial;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldRazaoSocial;
    // End of variables declaration//GEN-END:variables
}
