/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.telasCliente;

import controladores.ControladorCliente;

public class TelaCadastroCliente extends javax.swing.JPanel {

    public TelaCadastroCliente() {

        initComponents();
        // MASCARAS DE FORMATAÇÃO
        try {
            // CPF
            javax.swing.text.MaskFormatter mascaraCpf = new javax.swing.text.MaskFormatter("###.###.###-##");
            mascaraCpf.setPlaceholderCharacter('_'); // Define o caractere de preenchimento
            jFormattedTextFieldCpfCli.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascaraCpf)
            );

            // Máscara para Telefone Celular (padrão de 9 dígitos + DDD)
            javax.swing.text.MaskFormatter mascaraTelefone = new javax.swing.text.MaskFormatter("(##) #####-####");
            mascaraTelefone.setPlaceholderCharacter('_');

            // Aplica ao seu componente JFormattedTextField do telefone
            jFormattedTextFieldTelefoneCli.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascaraTelefone)
            );

            // CEP
            javax.swing.text.MaskFormatter mascaraCep = new javax.swing.text.MaskFormatter("#####-###");
            mascaraCep.setPlaceholderCharacter('_');
            jFormattedTextFieldCepCli.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascaraCep)
            );

        } catch (java.text.ParseException ex) {
            // Trata um eventual erro de digitação na string da máscara ("###...")
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeCli = new javax.swing.JLabel();
        jLabelCpfCli = new javax.swing.JLabel();
        jLabelEmailCli = new javax.swing.JLabel();
        jLabel1TelefoneCli = new javax.swing.JLabel();
        jLabelLogradouroCli = new javax.swing.JLabel();
        jLabelNumeroCli = new javax.swing.JLabel();
        jLabelBairroCli = new javax.swing.JLabel();
        jLabelCidadeCli = new javax.swing.JLabel();
        jLabelEstadoCli = new javax.swing.JLabel();
        jLabelCepCli = new javax.swing.JLabel();
        jTextFieldNomeCli = new javax.swing.JTextField();
        jTextFieldEmailCli = new javax.swing.JTextField();
        jTextFieldLogradouroCli = new javax.swing.JTextField();
        jTextFieldNumeroCli = new javax.swing.JTextField();
        jTextFieldBairroCli = new javax.swing.JTextField();
        jTextFieldCidadeCli = new javax.swing.JTextField();
        jComboBoxEstadoCli = new javax.swing.JComboBox<>();
        jButtonVoltarCli = new javax.swing.JButton();
        jButtonCadastrarCli = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jFormattedTextFieldCpfCli = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCepCli = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefoneCli = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabelNomeCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNomeCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomeCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNomeCli.setText("Nome");

        jLabelCpfCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCpfCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCpfCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCpfCli.setText("CPF");

        jLabelEmailCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmailCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEmailCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEmailCli.setText("E-mail");

        jLabel1TelefoneCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1TelefoneCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1TelefoneCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1TelefoneCli.setText("Telefone");

        jLabelLogradouroCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLogradouroCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLogradouroCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLogradouroCli.setText("Logradouro");

        jLabelNumeroCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNumeroCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumeroCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNumeroCli.setText("Número");

        jLabelBairroCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBairroCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBairroCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBairroCli.setText("Bairro");

        jLabelCidadeCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCidadeCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCidadeCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCidadeCli.setText("Cidade");

        jLabelEstadoCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEstadoCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstadoCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEstadoCli.setText("Estado");

        jLabelCepCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCepCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCepCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCepCli.setText("CEP");

        jComboBoxEstadoCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jButtonVoltarCli.setBackground(new java.awt.Color(255, 51, 51));
        jButtonVoltarCli.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVoltarCli.setText("Voltar");

        jButtonCadastrarCli.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCadastrarCli.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastrarCli.setText("Cadastrar");
        jButtonCadastrarCli.addActionListener(this::jButtonCadastrarCliActionPerformed);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("CADASTRO DE CLIENTES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNomeCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLogradouroCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCpfCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEmailCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1TelefoneCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNumeroCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelBairroCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCidadeCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEstadoCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCepCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEstadoCli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNomeCli)
                            .addComponent(jTextFieldEmailCli)
                            .addComponent(jTextFieldLogradouroCli)
                            .addComponent(jTextFieldNumeroCli)
                            .addComponent(jTextFieldBairroCli)
                            .addComponent(jTextFieldCidadeCli)
                            .addComponent(jFormattedTextFieldCpfCli)
                            .addComponent(jFormattedTextFieldCepCli)
                            .addComponent(jFormattedTextFieldTelefoneCli))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 111, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonVoltarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jButtonCadastrarCli)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelTitulo)
                                .addGap(115, 115, 115))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCli)
                    .addComponent(jTextFieldNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpfCli)
                    .addComponent(jFormattedTextFieldCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailCli)
                    .addComponent(jTextFieldEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1TelefoneCli)
                    .addComponent(jFormattedTextFieldTelefoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogradouroCli)
                    .addComponent(jTextFieldLogradouroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroCli)
                    .addComponent(jTextFieldNumeroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairroCli)
                    .addComponent(jTextFieldBairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidadeCli)
                    .addComponent(jTextFieldCidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstadoCli)
                    .addComponent(jComboBoxEstadoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCepCli)
                    .addComponent(jFormattedTextFieldCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarCli)
                    .addComponent(jButtonCadastrarCli))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarCliActionPerformed
        String nome = jTextFieldNomeCli.getText();
        String cpf = jFormattedTextFieldCpfCli.getText();
        String email = jTextFieldEmailCli.getText();

        // Expressão regular padrão para validar se o e-mail possui um formato válido
        String regexEmail = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        // Se o e-mail digitado não bater com o padrão, barra o cadastro
        if (!email.matches(regexEmail)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, insira um endereço de e-mail válido!",
                    "E-mail Inválido",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

            jTextFieldEmailCli.requestFocus();
            return;
        }

        String telefone = jFormattedTextFieldTelefoneCli.getText();
        String logradouro = jTextFieldLogradouroCli.getText();
        String numero = jTextFieldNumeroCli.getText();
        String bairro = jTextFieldBairroCli.getText();
        String cidade = jTextFieldCidadeCli.getText();
        String estado = jComboBoxEstadoCli.getSelectedItem().toString();
        String cep = jFormattedTextFieldCepCli.getText();

        // 1. Envia os dados para salvar
        int idCliente = ControladorCliente.getInstanciaControladorCliente().cadastrarClienteGrafico(nome, cpf, email, telefone, logradouro, numero, bairro, cidade, estado, cep);

        // =================================================================
        // NOVOS COMPORTAMENTOS: AVISO E LIMPEZA
        // =================================================================
        // 2. Mostra a caixinha de aviso de Sucesso
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Cliente '" + nome + "' cadastrado com sucesso no ID "+idCliente,
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        // 3. Limpa todos os campos da tela
        jTextFieldNomeCli.setText("");
        jFormattedTextFieldCpfCli.setValue(null);
        jTextFieldEmailCli.setText("");
        jFormattedTextFieldTelefoneCli.setValue(null);
        jTextFieldLogradouroCli.setText("");
        jTextFieldNumeroCli.setText("");
        jTextFieldBairroCli.setText("");
        jTextFieldCidadeCli.setText("");
        jComboBoxEstadoCli.setSelectedIndex(0);
        jFormattedTextFieldCepCli.setValue(null);

        // 4. Coloca o cursor piscando de volta no Nome do cliente
        jTextFieldNomeCli.requestFocus();
    }//GEN-LAST:event_jButtonCadastrarCliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarCli;
    private javax.swing.JButton jButtonVoltarCli;
    private javax.swing.JComboBox<String> jComboBoxEstadoCli;
    private javax.swing.JFormattedTextField jFormattedTextFieldCepCli;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfCli;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefoneCli;
    private javax.swing.JLabel jLabel1TelefoneCli;
    private javax.swing.JLabel jLabelBairroCli;
    private javax.swing.JLabel jLabelCepCli;
    private javax.swing.JLabel jLabelCidadeCli;
    private javax.swing.JLabel jLabelCpfCli;
    private javax.swing.JLabel jLabelEmailCli;
    private javax.swing.JLabel jLabelEstadoCli;
    private javax.swing.JLabel jLabelLogradouroCli;
    private javax.swing.JLabel jLabelNomeCli;
    private javax.swing.JLabel jLabelNumeroCli;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldBairroCli;
    private javax.swing.JTextField jTextFieldCidadeCli;
    private javax.swing.JTextField jTextFieldEmailCli;
    private javax.swing.JTextField jTextFieldLogradouroCli;
    private javax.swing.JTextField jTextFieldNomeCli;
    private javax.swing.JTextField jTextFieldNumeroCli;
    // End of variables declaration//GEN-END:variables
}
