/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.telasCliente;

/**
 *
 * @author Mario
 */
public class TelaMenuCliente extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuCliente.class.getName());

    
    public TelaMenuCliente() {
        initComponents();
        
        // 1. Maximiza a janela
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        // =================================================================
        // CENTRALIZAÇÃO HORIZONTAL DO MENU LATERAL (jPanelMenu1)
        // =================================================================
        jPanelMenu1.setLayout(new javax.swing.BoxLayout(jPanelMenu1, javax.swing.BoxLayout.Y_AXIS));
        
        float centroX = java.awt.Component.CENTER_ALIGNMENT;
        
        // --- DEFINE UMA LARGURA PADRÃO PARA TODOS OS BOTÕES ---
        // 140 pixels de largura por 30 pixels de altura (ajuste como preferir)
        java.awt.Dimension tamanhoBotao = new java.awt.Dimension(140, 30);
        
        jButtonCadastrarCli1.setMaximumSize(tamanhoBotao);
        jButtonAtualizarCli1.setMaximumSize(tamanhoBotao);
        jButtonConsultarCli1.setMaximumSize(tamanhoBotao);
        jButtonListarCli1.setMaximumSize(tamanhoBotao);
        jButtonSairCli1.setMaximumSize(tamanhoBotao);
        // -----------------------------------------------------
        
        // Aplica o alinhamento horizontal no centro para cada componente
        jLabelMenu1.setAlignmentX(centroX);
        jButtonCadastrarCli1.setAlignmentX(centroX);
        jButtonAtualizarCli1.setAlignmentX(centroX);
        jButtonConsultarCli1.setAlignmentX(centroX);
        jButtonListarCli1.setAlignmentX(centroX);
        jButtonSairCli1.setAlignmentX(centroX);
        
        // Reconstrói o menu adicionando pequenos espaçamentos verticais entre eles
        jPanelMenu1.removeAll();
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(15)); 
        jPanelMenu1.add(jLabelMenu1);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(20)); 
        jPanelMenu1.add(jButtonCadastrarCli1);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonAtualizarCli1);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonConsultarCli1);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(10));
        jPanelMenu1.add(jButtonListarCli1);
        jPanelMenu1.add(javax.swing.Box.createVerticalStrut(15));
        jPanelMenu1.add(jButtonSairCli1);
        
        // =================================================================
        // CENTRALIZAÇÃO HORIZONTAL DA ÁREA DE CONTEÚDO (jPanelTela)
        // =================================================================
        // Mesma lógica: empilha de cima para baixo, centralizado na horizontal
        jPanelTela.setLayout(new javax.swing.BoxLayout(jPanelTela, javax.swing.BoxLayout.Y_AXIS));
        
        jLabelBemVindoCli.setAlignmentX(centroX);
        
        jPanelTela.removeAll();
        jPanelTela.add(javax.swing.Box.createVerticalStrut(20)); // Margem do topo da tela
        jPanelTela.add(jLabelBemVindoCli);
        
        // Força a atualização do layout
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMenu1 = new javax.swing.JPanel();
        jLabelMenu1 = new javax.swing.JLabel();
        jButtonCadastrarCli1 = new javax.swing.JButton();
        jButtonAtualizarCli1 = new javax.swing.JButton();
        jButtonConsultarCli1 = new javax.swing.JButton();
        jButtonListarCli1 = new javax.swing.JButton();
        jButtonSairCli1 = new javax.swing.JButton();
        jPanelTela = new javax.swing.JPanel();
        jLabelBemVindoCli = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelMenu1.setBackground(new java.awt.Color(102, 102, 255));

        jLabelMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMenu1.setText("MENU");

        jButtonCadastrarCli1.setText("Cadastrar clientes");
        jButtonCadastrarCli1.addActionListener(this::jButtonCadastrarCli1ActionPerformed);

        jButtonAtualizarCli1.setText("Atualizar clientes");

        jButtonConsultarCli1.setText("Consultar clientes");

        jButtonListarCli1.setText("Listar clientes");
        jButtonListarCli1.addActionListener(this::jButtonListarCli1ActionPerformed);

        jButtonSairCli1.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSairCli1.setText("Sair");

        javax.swing.GroupLayout jPanelMenu1Layout = new javax.swing.GroupLayout(jPanelMenu1);
        jPanelMenu1.setLayout(jPanelMenu1Layout);
        jPanelMenu1Layout.setHorizontalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrarCli1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConsultarCli1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAtualizarCli1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListarCli1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSairCli1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
            .addGroup(jPanelMenu1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabelMenu1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenu1Layout.setVerticalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenu1)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastrarCli1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAtualizarCli1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConsultarCli1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListarCli1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSairCli1)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelMenu1, java.awt.BorderLayout.LINE_START);

        jPanelTela.setBackground(new java.awt.Color(153, 153, 255));

        jLabelBemVindoCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBemVindoCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBemVindoCli.setText("Bem vindo ao módulo Clientes");

        javax.swing.GroupLayout jPanelTelaLayout = new javax.swing.GroupLayout(jPanelTela);
        jPanelTela.setLayout(jPanelTelaLayout);
        jPanelTelaLayout.setHorizontalGroup(
            jPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTelaLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabelBemVindoCli)
                .addGap(36, 36, 36))
        );
        jPanelTelaLayout.setVerticalGroup(
            jPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBemVindoCli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelTela, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarCli1ActionPerformed
        // 1. Limpa o painel principal da direita
        jPanelTela.removeAll();
        
        // 2. Define o layout do jPanelTela para GridBagLayout (ele vai garantir a centralização)
        jPanelTela.setLayout(new java.awt.GridBagLayout());
        
        // 3. Instancia a tela de cadastro normalmente
        TelaCadastroCliente telaCadastro = new TelaCadastroCliente();
        
        // 4. Cria um painel intermediário invisível para limitar a largura do formulário
        javax.swing.JPanel limitadorLargura = new javax.swing.JPanel();
        limitadorLargura.setLayout(new java.awt.BorderLayout());
        limitadorLargura.setBackground(telaCadastro.getBackground()); // Mantém a cor azul de fundo
        
        // Define o tamanho máximo desejado (450px de largura por 420px de altura)
        java.awt.Dimension tamanhoMaximo = new java.awt.Dimension(450, 420);
        limitadorLargura.setPreferredSize(tamanhoMaximo);
        limitadorLargura.setMinimumSize(tamanhoMaximo);
        limitadorLargura.setMaximumSize(tamanhoMaximo);
        
        // 5. Adiciona a tela de cadastro para preencher esse limitador
        limitadorLargura.add(telaCadastro, java.awt.BorderLayout.CENTER);
        
        // 6. Configura o GridBagLayout para fixar o limitador morto no centro do jPanelTela
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER; // Força a centralização horizontal e vertical
        
        // Adiciona o bloco estruturado ao painel principal
        jPanelTela.add(limitadorLargura, gbc);
        
        // 7. Atualiza e renderiza os novos componentes na interface
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonCadastrarCli1ActionPerformed

    private void jButtonListarCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarCli1ActionPerformed
        // 1. Limpa a área de conteúdo atual
        jPanelTela.removeAll();
        
        // 2. Define o layout como BorderLayout para a tabela expandir e ocupar o espaço útil da direita
        jPanelTela.setLayout(new java.awt.BorderLayout());
        
        // 3. Instancia a tela de listagem que criamos
        TelaListarClientes telaListar = new TelaListarClientes();
        
        // 4. Adiciona ao centro do painel com uma pequena borda de respiro (margem nas laterais)
        telaListar.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanelTela.add(telaListar, java.awt.BorderLayout.CENTER);
        
        // 5. Atualiza e redesenha a tela
        jPanelTela.revalidate();
        jPanelTela.repaint();
    }//GEN-LAST:event_jButtonListarCli1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenuCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarCli1;
    private javax.swing.JButton jButtonCadastrarCli1;
    private javax.swing.JButton jButtonConsultarCli1;
    private javax.swing.JButton jButtonListarCli1;
    private javax.swing.JButton jButtonSairCli1;
    private javax.swing.JLabel jLabelBemVindoCli;
    private javax.swing.JLabel jLabelMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenu1;
    private javax.swing.JPanel jPanelTela;
    // End of variables declaration//GEN-END:variables
}
